In [62]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
import time

In [63]:
URL = 'https://www.flipkart.com/search?q=phone&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&p%5B%5D=facets.price_range.from%3D20000&p%5B%5D=facets.price_range.to%3DMax&page=1'
page = requests.get(URL)
page.status_code

403

### Without Headers
Your request looks like:

“Hi, I am a script. Definitely not a bot. Trust me.”

Flipkart:

“403. Go away.”

### What is User-Agent?
When you visit a website, your browser sends info like:

Browser name (Chrome, Firefox)

OS (Windows, Mac)
Device type

Example:
Chrome on Windows → Mozilla/5.0 ..

### With headers:

Now your request says:

“Hello, I am Chrome browser on Windows.”

Flipkart:

“Alright, come in.”

In [64]:

URL = 'https://www.flipkart.com/search?q=phone&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&p%5B%5D=facets.price_range.from%3D20000&p%5B%5D=facets.price_range.to%3DMax&page=1'

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36"
}

page = requests.get(URL, headers=headers)

print(page.status_code)

200

In [65]:
#It returns the raw data (in bytes) that the server sent back.
page.content

b'<!doctype html><html lang="en"><head><link href="https://rukminim2.flixcart.com" rel="preconnect"/><link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/bundle.aa1465.css"/><link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/bundle.fbaef9.css"/><meta http-equiv="Content-type" content="text/html; charset=utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=Edge"/><meta property="fb:page_id" content="102988293558"/><meta property="fb:admins" content="658873552,624500995,100000233612389"/><link rel="shortcut icon" href="https://static-assets-web.flixcart.com/www/promos/new/20150528-140547-favicon-retina.ico"/><link type="application/opensearchdescription+xml" rel="search" href="/osdd.xml?v=2"/><meta property="og:type" content="website"/><meta name="og_site_name" property="og:site_name" content="Flipkart.com"/><link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png"/><link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png"/><link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png"/><link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png"/><link rel="apple-touch-icon" href="/apple-touch-icon-57x57.png"/><meta name="twitter:card" content="app"><meta name="twitter:site" content="@flipkart"><meta name="twitter:creator" content="@flipkart"><meta name="twitter:title" content="Phone- Buy Products Online at Best Price in India - All Categories | Flipkart.com"><meta name="twitter:description" content="Shop for electronics, apparels & more using our Flipkart app Free shipping & COD."><meta name="twitter:app:country" content="in"><meta name="al:ios:app_name" content="Flipkart"><meta name="al:ios:app_store_id" content="742044692"><meta name="twitter:app:name:iphone" content="Flipkart"><meta name="twitter:app:id:iphone" content="742044692"><meta name="twitter:app:url:iphone" content="http://dl.flipkart.com/dl/home?"><meta name="twitter:app:name:ipad" content="Flipkart"><meta name="twitter:app:id:ipad" content="742044692"><meta name="twitter:app:url:ipad" content="http://dl.flipkart.com/dl/home?"><meta name="twitter:app:name:googleplay" content="Flipkart"><meta name="twitter:app:id:googleplay" content="com.flipkart.android"><meta name="twitter:app:url:googleplay" content="http://dl.flipkart.com/dl/home?"><style>#container {\n\t\t\theight: 100%;\n\t\t}</style> <script src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/runtime.603c0af2.js" defer="defer" crossorigin="anonymous"></script><script src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/vendor.79dfd802.js" defer="defer" crossorigin="anonymous"></script><script src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_common.5fd330b1.js" defer="defer" crossorigin="anonymous"></script><script src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_modules.92a0f463.js" defer="defer" crossorigin="anonymous"></script><script src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app.572e15e1.js" defer="defer" crossorigin="anonymous"></script> <link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/Browse.chunk.647087.css"/><title>Phone- Buy Products Online at Best Price in India - All Categories | Flipkart.com</title><meta name="og_title" property="og:title" content="Phone- Buy Products Online at Best Price in India - All Categories | Flipkart.com"/><meta name="Keywords" content="Phone"/> <meta name="Description" content="Phone- Buy Products Online at Best Price in India. India&#x27;s Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com"/><meta property="og:description" content="Phone- Buy Products Online at Best Price in India. India&#x27;s Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com"/>       <meta name="msvalidate.01" content="F4EEB3A0AFFDD385992A06E6920C0AC3"/> <!--[if IE 9 ]>\n\t<script nonce="18393894387124668698">\n\t\twindow.browserVersion = \'IE9\';\n\t\tdocument.documentElement.className += \' ie9\';\n\t</script>\n\t<![endif]--><!--[if !IE]><!--><script nonce="18393894387124668698">if (/*@cc_on!@*/false) {\n\t\t\twindow.browserVersion = \'IE10\';\n\t\t\tdocument.documentElement.className += \' ie10\';\n\t\t}</script><!--<![endif]--> <script nonce="18393894387124668698">;window.NREUM||(NREUM={});NREUM.init={distributed_tracing:{enabled:true},privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]}};\n\n\t\t\t;NREUM.loader_config={accountID:"3700282",trustKey:"3679896",agentID:"1588759528",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528"}\n\t\t\t;NREUM.info={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528",sa:1}\n\n\t\t\t;/*! For license information please see nr-loader-spa-1.236.0.min.js.LICENSE.txt */\n\t\t\t(()=>{"use strict";var e,t,r={5763:(e,t,r)=>{r.d(t,{P_:()=>l,Mt:()=>g,C5:()=>s,DL:()=>v,OP:()=>T,lF:()=>D,Yu:()=>y,Dg:()=>h,CX:()=>c,GE:()=>b,sU:()=>_});var n=r(8632),i=r(9567);const o={beacon:n.ce.beacon,errorBeacon:n.ce.errorBeacon,licenseKey:void 0,applicationID:void 0,sa:void 0,queueTime:void 0,applicationTime:void 0,ttGuid:void 0,user:void 0,account:void 0,product:void 0,extra:void 0,jsAttributes:{},userAttributes:void 0,atts:void 0,transactionName:void 0,tNamePlain:void 0},a={};function s(e){if(!e)throw new Error("All info objects require an agent identifier!");if(!a[e])throw new Error("Info for ".concat(e," was never set"));return a[e]}function c(e,t){if(!e)throw new Error("All info objects require an agent identifier!");a[e]=(0,i.D)(t,o),(0,n.Qy)(e,a[e],"info")}var u=r(7056);const d=()=>{const e={blockSelector:"[data-nr-block]",maskInputOptions:{password:!0}};return{allow_bfcache:!0,privacy:{cookies_enabled:!0},ajax:{deny_list:void 0,enabled:!0,harvestTimeSeconds:10},distributed_tracing:{enabled:void 0,exclude_newrelic_header:void 0,cors_use_newrelic_header:void 0,cors_use_tracecontext_headers:void 0,allowed_origins:void 0},session:{domain:void 0,expiresMs:u.oD,inactiveMs:u.Hb},ssl:void 0,obfuscate:void 0,jserrors:{enabled:!0,harvestTimeSeconds:10},metrics:{enabled:!0},page_action:{enabled:!0,harvestTimeSeconds:30},page_view_event:{enabled:!0},page_view_timing:{enabled:!0,harvestTimeSeconds:30,long_task:!1},session_trace:{enabled:!0,harvestTimeSeconds:10},harvest:{tooManyRequestsDelay:60},session_replay:{enabled:!1,harvestTimeSeconds:60,sampleRate:.1,errorSampleRate:.1,maskTextSelector:"*",maskAllInputs:!0,get blockClass(){return"nr-block"},get ignoreClass(){return"nr-ignore"},get maskTextClass(){return"nr-mask"},get blockSelector(){return e.blockSelector},set blockSelector(t){e.blockSelector+=",".concat(t)},get maskInputOptions(){return e.maskInputOptions},set maskInputOptions(t){e.maskInputOptions={...t,password:!0}}},spa:{enabled:!0,harvestTimeSeconds:10}}},f={};function l(e){if(!e)throw new Error("All configuration objects require an agent identifier!");if(!f[e])throw new Error("Configuration for ".concat(e," was never set"));return f[e]}function h(e,t){if(!e)throw new Error("All configuration objects require an agent identifier!");f[e]=(0,i.D)(t,d()),(0,n.Qy)(e,f[e],"config")}function g(e,t){if(!e)throw new Error("All configuration objects require an agent identifier!");var r=l(e);if(r){for(var n=t.split("."),i=0;i<n.length-1;i++)if("object"!=typeof(r=r[n[i]]))return;r=r[n[n.length-1]]}return r}const p={accountID:void 0,trustKey:void 0,agentID:void 0,licenseKey:void 0,applicationID:void 0,xpid:void 0},m={};function v(e){if(!e)throw new Error("All loader-config objects require an agent identifier!");if(!m[e])throw new Error("LoaderConfig for ".concat(e," was never set"));return m[e]}function b(e,t){if(!e)throw new Error("All loader-config objects require an agent identifier!");m[e]=(0,i.D)(t,p),(0,n.Qy)(e,m[e],"loader_config")}const y=(0,n.mF)().o;var w=r(385),x=r(6818);const A={buildEnv:x.Re,bytesSent:{},queryBytesSent:{},customTransaction:void 0,disabled:!1,distMethod:x.gF,isolatedBacklog:!1,loaderType:void 0,maxBytes:3e4,offset:Math.floor(w._A?.performance?.timeOrigin||w._A?.performance?.timing?.navigationStart||Date.now()),onerror:void 0,origin:""+w._A.location,ptid:void 0,releaseIds:{},session:void 0,xhrWrappable:"function"==typeof w._A.XMLHttpRequest?.prototype?.addEventListener,version:x.q4},E={};function T(e){if(!e)throw new Error("All runtime objects require an agent identifier!");if(!E[e])throw new Error("Runtime for ".concat(e," was never set"));return E[e]}function _(e,t){if(!e)throw new Error("All runtime objects require an agent identifier!");E[e]=(0,i.D)(t,A),(0,n.Qy)(e,E[e],"runtime")}function D(e){return function(e){try{const t=s(e);return!!t.licenseKey&&!!t.errorBeacon&&!!t.applicationID}catch(e){return!1}}(e)}},9567:(e,t,r)=>{r.d(t,{D:()=>i});var n=r(50);function i(e,t){try{if(!e||"object"!=typeof e)return(0,n.Z)("Setting a Configurable requires an object as input");if(!t||"object"!=typeof t)return(0,n.Z)("Setting a Configurable requires a model to set its initial properties");const r=Object.create(Object.getPrototypeOf(t),Object.getOwnPropertyDescriptors(t)),o=0===Object.keys(r).length?e:r;for(let a in o)if(void 0!==e[a])try{"object"==typeof e[a]&&"object"==typeof t[a]?r[a]=i(e[a],t[a]):r[a]=e[a]}catch(e){(0,n.Z)("An error occurred while setting a property of a Configurable",e)}return r}catch(e){(0,n.Z)("An error occured while setting a Configurable",e)}}},6818:(e,t,r)=>{r.d(t,{Re:()=>i,gF:()=>o,q4:()=>n});const n="1.236.0",i="PROD",o="CDN"},385:(e,t,r)=>{r.d(t,{FN:()=>a,IF:()=>u,Nk:()=>f,Tt:()=>s,_A:()=>o,il:()=>n,pL:()=>c,v6:()=>i,w1:()=>d});const n="undefined"!=typeof window&&!!window.document,i="undefined"!=typeof WorkerGlobalScope&&("undefined"!=typeof self&&self instanceof WorkerGlobalScope&&self.navigator instanceof WorkerNavigator||"undefined"!=typeof globalThis&&globalThis instanceof WorkerGlobalScope&&globalThis.navigator instanceof WorkerNavigator),o=n?window:"undefined"!=typeof WorkerGlobalScope&&("undefined"!=typeof self&&self instanceof WorkerGlobalScope&&self||"undefined"!=typeof globalThis&&globalThis instanceof WorkerGlobalScope&&globalThis),a=""+o?.location,s=/iPad|iPhone|iPod/.test(navigator.userAgent),c=s&&"undefined"==typeof SharedWorker,u=(()=>{const e=navigator.userAgent.match(/Firefox[/\\s](\\d+\\.\\d+)/);return Array.isArray(e)&&e.length>=2?+e[1]:0})(),d=Boolean(n&&window.document.documentMode),f=!!navigator.sendBeacon},1117:(e,t,r)=>{r.d(t,{w:()=>o});var n=r(50);const i={agentIdentifier:"",ee:void 0};class o{constructor(e){try{if("object"!=typeof e)return(0,n.Z)("shared context requires an object as input");this.sharedContext={},Object.assign(this.sharedContext,i),Object.entries(e).forEach((e=>{let[t,r]=e;Object.keys(i).includes(t)&&(this.sharedContext[t]=r)}))}catch(e){(0,n.Z)("An error occured while setting SharedContext",e)}}}},8e3:(e,t,r)=>{r.d(t,{L:()=>d,R:()=>c});var n=r(2177),i=r(1284),o=r(4322),a=r(3325);const s={};function c(e,t){const r={staged:!1,priority:a.p[t]||0};u(e),s[e].get(t)||s[e].set(t,r)}function u(e){e&&(s[e]||(s[e]=new Map))}function d(){let e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:"",t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:"feature";if(u(e),!e||!s[e].get(t))return a(t);s[e].get(t).staged=!0;const r=[...s[e]];function a(t){const r=e?n.ee.get(e):n.ee,a=o.X.handlers;if(r.backlog&&a){var s=r.backlog[t],c=a[t];if(c){for(var u=0;s&&u<s.length;++u)f(s[u],c);(0,i.D)(c,(function(e,t){(0,i.D)(t,(function(t,r){r[0].on(e,r[1])}))}))}delete a[t],r.backlog[t]=null,r.emit("drain-"+t,[])}}r.every((e=>{let[t,r]=e;return r.staged}))&&(r.sort(((e,t)=>e[1].priority-t[1].priority)),r.forEach((e=>{let[t]=e;a(t)})))}function f(e,t){var r=e[1];(0,i.D)(t[r],(function(t,r){var n=e[0];if(r[0]===n){var i=r[1],o=e[3],a=e[2];i.apply(o,a)}}))}},2177:(e,t,r)=>{r.d(t,{c:()=>f,ee:()=>u});var n=r(8632),i=r(2210),o=r(1284),a=r(5763),s="nr@context";let c=(0,n.fP)();var u;function d(){}function f(e){return(0,i.X)(e,s,l)}function l(){return new d}function h(){u.aborted=!0,u.backlog={}}c.ee?u=c.ee:(u=function e(t,r){var n={},c={},f={},g=!1;try{g=16===r.length&&(0,a.OP)(r).isolatedBacklog}catch(e){}var p={on:b,addEventListener:b,removeEventListener:y,emit:v,get:x,listeners:w,context:m,buffer:A,abort:h,aborted:!1,isBuffering:E,debugId:r,backlog:g?{}:t&&"object"==typeof t.backlog?t.backlog:{}};return p;function m(e){return e&&e instanceof d?e:e?(0,i.X)(e,s,l):l()}function v(e,r,n,i,o){if(!1!==o&&(o=!0),!u.aborted||i){t&&o&&t.emit(e,r,n);for(var a=m(n),s=w(e),d=s.length,f=0;f<d;f++)s[f].apply(a,r);var l=T()[c[e]];return l&&l.push([p,e,r,a]),a}}function b(e,t){n[e]=w(e).concat(t)}function y(e,t){var r=n[e];if(r)for(var i=0;i<r.length;i++)r[i]===t&&r.splice(i,1)}function w(e){return n[e]||[]}function x(t){return f[t]=f[t]||e(p,t)}function A(e,t){var r=T();p.aborted||(0,o.D)(e,(function(e,n){t=t||"feature",c[n]=t,t in r||(r[t]=[])}))}function E(e){return!!T()[c[e]]}function T(){return p.backlog}}(void 0,"globalEE"),c.ee=u)},5546:(e,t,r)=>{r.d(t,{E:()=>n,p:()=>i});var n=r(2177).ee.get("handle");function i(e,t,r,i,o){o?(o.buffer([e],i),o.emit(e,t,r)):(n.buffer([e],i),n.emit(e,t,r))}},4322:(e,t,r)=>{r.d(t,{X:()=>o});var n=r(5546);o.on=a;var i=o.handlers={};function o(e,t,r,o){a(o||n.E,i,e,t,r)}function a(e,t,r,i,o){o||(o="feature"),e||(e=n.E);var a=t[o]=t[o]||{};(a[r]=a[r]||[]).push([e,i])}},3239:(e,t,r)=>{r.d(t,{bP:()=>s,iz:()=>c,m$:()=>a});var n=r(385);let i=!1,o=!1;try{const e={get passive(){return i=!0,!1},get signal(){return o=!0,!1}};n._A.addEventListener("test",null,e),n._A.removeEventListener("test",null,e)}catch(e){}function a(e,t){return i||o?{capture:!!e,passive:i,signal:t}:!!e}function s(e,t){let r=arguments.length>2&&void 0!==arguments[2]&&arguments[2],n=arguments.length>3?arguments[3]:void 0;window.addEventListener(e,t,a(r,n))}function c(e,t){let r=arguments.length>2&&void 0!==arguments[2]&&arguments[2],n=arguments.length>3?arguments[3]:void 0;document.addEventListener(e,t,a(r,n))}},4402:(e,t,r)=>{r.d(t,{Ht:()=>u,M:()=>c,Rl:()=>a,ky:()=>s});var n=r(385);const i="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx";function o(e,t){return e?15&e[t]:16*Math.random()|0}function a(){const e=n._A?.crypto||n._A?.msCrypto;let t,r=0;return e&&e.getRandomValues&&(t=e.getRandomValues(new Uint8Array(31))),i.split("").map((e=>"x"===e?o(t,++r).toString(16):"y"===e?(3&o()|8).toString(16):e)).join("")}function s(e){const t=n._A?.crypto||n._A?.msCrypto;let r,i=0;t&&t.getRandomValues&&(r=t.getRandomValues(new Uint8Array(31)));const a=[];for(var s=0;s<e;s++)a.push(o(r,++i).toString(16));return a.join("")}function c(){return s(16)}function u(){return s(32)}},7056:(e,t,r)=>{r.d(t,{Bq:()=>n,Hb:()=>o,oD:()=>i});const n="NRBA",i=144e5,o=18e5},7894:(e,t,r)=>{function n(){return Math.round(performance.now())}r.d(t,{z:()=>n})},7243:(e,t,r)=>{r.d(t,{e:()=>o});var n=r(385),i={};function o(e){if(e in i)return i[e];if(0===(e||"").indexOf("data:"))return{protocol:"data"};let t;var r=n._A?.location,o={};if(n.il)t=document.createElement("a"),t.href=e;else try{t=new URL(e,r.href)}catch(e){return o}o.port=t.port;var a=t.href.split("://");!o.port&&a[1]&&(o.port=a[1].split("/")[0].split("@").pop().split(":")[1]),o.port&&"0"!==o.port||(o.port="https"===a[0]?"443":"80"),o.hostname=t.hostname||r.hostname,o.pathname=t.pathname,o.protocol=a[0],"/"!==o.pathname.charAt(0)&&(o.pathname="/"+o.pathname);var s=!t.protocol||":"===t.protocol||t.protocol===r.protocol,c=t.hostname===r.hostname&&t.port===r.port;return o.sameOrigin=s&&(!t.hostname||c),"/"===o.pathname&&(i[e]=o),o}},50:(e,t,r)=>{function n(e,t){"function"==typeof console.warn&&(console.warn("New Relic: ".concat(e)),t&&console.warn(t))}r.d(t,{Z:()=>n})},2587:(e,t,r)=>{r.d(t,{N:()=>c,T:()=>u});var n=r(2177),i=r(5546),o=r(8e3),a=r(3325);const s={stn:[a.D.sessionTrace],err:[a.D.jserrors,a.D.metrics],ins:[a.D.pageAction],spa:[a.D.spa],sr:[a.D.sessionReplay,a.D.sessionTrace]};function c(e,t){const r=n.ee.get(t);e&&"object"==typeof e&&(Object.entries(e).forEach((e=>{let[t,n]=e;void 0===u[t]&&(s[t]?s[t].forEach((e=>{n?(0,i.p)("feat-"+t,[],void 0,e,r):(0,i.p)("block-"+t,[],void 0,e,r),(0,i.p)("rumresp-"+t,[Boolean(n)],void 0,e,r)})):n&&(0,i.p)("feat-"+t,[],void 0,void 0,r),u[t]=Boolean(n))})),Object.keys(s).forEach((e=>{void 0===u[e]&&(s[e]?.forEach((t=>(0,i.p)("rumresp-"+e,[!1],void 0,t,r))),u[e]=!1)})),(0,o.L)(t,a.D.pageViewEvent))}const u={}},2210:(e,t,r)=>{r.d(t,{X:()=>i});var n=Object.prototype.hasOwnProperty;function i(e,t,r){if(n.call(e,t))return e[t];var i=r();if(Object.defineProperty&&Object.keys)try{return Object.defineProperty(e,t,{value:i,writable:!0,enumerable:!1}),i}catch(e){}return e[t]=i,i}},1284:(e,t,r)=>{r.d(t,{D:()=>n});const n=(e,t)=>Object.entries(e||{}).map((e=>{let[r,n]=e;return t(r,n)}))},4351:(e,t,r)=>{r.d(t,{P:()=>o});var n=r(2177);const i=()=>{const e=new WeakSet;return(t,r)=>{if("object"==typeof r&&null!==r){if(e.has(r))return;e.add(r)}return r}};function o(e){try{return JSON.stringify(e,i())}catch(e){try{n.ee.emit("internal-error",[e])}catch(e){}}}},3960:(e,t,r)=>{r.d(t,{K:()=>a,b:()=>o});var n=r(3239);function i(){return"undefined"==typeof document||"complete"===document.readyState}function o(e,t){if(i())return e();(0,n.bP)("load",e,t)}function a(e){if(i())return e();(0,n.iz)("DOMContentLoaded",e)}},8632:(e,t,r)=>{r.d(t,{EZ:()=>u,Qy:()=>c,ce:()=>o,fP:()=>a,gG:()=>d,mF:()=>s});var n=r(7894),i=r(385);const o={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net"};function a(){return i._A.NREUM||(i._A.NREUM={}),void 0===i._A.newrelic&&(i._A.newrelic=i._A.NREUM),i._A.NREUM}function s(){let e=a();return e.o||(e.o={ST:i._A.setTimeout,SI:i._A.setImmediate,CT:i._A.clearTimeout,XHR:i._A.XMLHttpRequest,REQ:i._A.Request,EV:i._A.Event,PR:i._A.Promise,MO:i._A.MutationObserver,FETCH:i._A.fetch}),e}function c(e,t,r){let i=a();const o=i.initializedAgents||{},s=o[e]||{};return Object.keys(s).length||(s.initializedAt={ms:(0,n.z)(),date:new Date}),i.initializedAgents={...o,[e]:{...s,[r]:t}},i}function u(e,t){a()[e]=t}function d(){return function(){let e=a();const t=e.info||{};e.info={beacon:o.beacon,errorBeacon:o.errorBeacon,...t}}(),function(){let e=a();const t=e.init||{};e.init={...t}}(),s(),function(){let e=a();const t=e.loader_config||{};e.loader_config={...t}}(),a()}},7956:(e,t,r)=>{r.d(t,{N:()=>i});var n=r(3239);function i(e){let t=arguments.length>1&&void 0!==arguments[1]&&arguments[1],r=arguments.length>2?arguments[2]:void 0,i=arguments.length>3?arguments[3]:void 0;return void(0,n.iz)("visibilitychange",(function(){if(t)return void("hidden"==document.visibilityState&&e());e(document.visibilityState)}),r,i)}},1214:(e,t,r)=>{r.d(t,{em:()=>v,u5:()=>N,QU:()=>S,_L:()=>I,Gm:()=>L,Lg:()=>M,gy:()=>U,BV:()=>Q,Kf:()=>ee});var n=r(2177);const i="nr@original";var o=Object.prototype.hasOwnProperty,a=!1;function s(e,t){return e||(e=n.ee),r.inPlace=function(e,t,n,i,o){n||(n="");var a,s,c,u="-"===n.charAt(0);for(c=0;c<t.length;c++)d(a=e[s=t[c]])||(e[s]=r(a,u?s+n:n,i,s,o))},r.flag=i,r;function r(t,r,n,a,s){return d(t)?t:(r||(r=""),nrWrapper[i]=t,u(t,nrWrapper,e),nrWrapper);function nrWrapper(){var i,u,d,f;try{u=this,i=[...arguments],d="function"==typeof n?n(i,u):n||{}}catch(t){c([t,"",[i,u,a],d],e)}o(r+"start",[i,u,a],d,s);try{return f=t.apply(u,i)}catch(e){throw o(r+"err",[i,u,e],d,s),e}finally{o(r+"end",[i,u,f],d,s)}}}function o(r,n,i,o){if(!a||t){var s=a;a=!0;try{e.emit(r,n,i,t,o)}catch(t){c([t,r,n,i],e)}a=s}}}function c(e,t){t||(t=n.ee);try{t.emit("internal-error",e)}catch(e){}}function u(e,t,r){if(Object.defineProperty&&Object.keys)try{return Object.keys(e).forEach((function(r){Object.defineProperty(t,r,{get:function(){return e[r]},set:function(t){return e[r]=t,t}})})),t}catch(e){c([e],r)}for(var n in e)o.call(e,n)&&(t[n]=e[n]);return t}function d(e){return!(e&&e instanceof Function&&e.apply&&!e[i])}var f=r(2210),l=r(385);const h={},g=XM

In [66]:
soup = BeautifulSoup(page.content, 'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <link href="https://rukminim2.flixcart.com" rel="preconnect"/>
  <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/bundle.aa1465.css" rel="stylesheet"/>
  <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/bundle.fbaef9.css" rel="stylesheet"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-type"/>
  <meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
  <meta content="102988293558" property="fb:page_id"/>
  <meta content="658873552,624500995,100000233612389" property="fb:admins"/>
  <link href="https://static-assets-web.flixcart.com/www/promos/new/20150528-140547-favicon-retina.ico" rel="shortcut icon"/>
  <link href="/osdd.xml?v=2" rel="search" type="application/opensearchdescription+xml"/>
  <meta content="website" property="og:type"/>
  <meta content="Flipkart.com" name="og_site_name" property="og:site_name"/>
  <link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
  <link href="/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
  <link href="/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
  <link href="/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
  <link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon"/>
  <meta content="app" name="twitter:card"/>
  <meta content="@flipkart" name="twitter:site"/>
  <meta content="@flipkart" name="twitter:creator"/>
  <meta content="Phone- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="twitter:title"/>
  <meta content="Shop for electronics, apparels &amp; more using our Flipkart app Free shipping &amp; COD." name="twitter:description"/>
  <meta content="in" name="twitter:app:country"/>
  <meta content="Flipkart" name="al:ios:app_name"/>
  <meta content="742044692" name="al:ios:app_store_id"/>
  <meta content="Flipkart" name="twitter:app:name:iphone"/>
  <meta content="742044692" name="twitter:app:id:iphone"/>
  <meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:iphone"/>
  <meta content="Flipkart" name="twitter:app:name:ipad"/>
  <meta content="742044692" name="twitter:app:id:ipad"/>
  <meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:ipad"/>
  <meta content="Flipkart" name="twitter:app:name:googleplay"/>
  <meta content="com.flipkart.android" name="twitter:app:id:googleplay"/>
  <meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:googleplay"/>
  <style>
   #container {
			height: 100%;
		}
  </style>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/runtime.603c0af2.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/vendor.79dfd802.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_common.5fd330b1.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_modules.92a0f463.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app.572e15e1.js">
  </script>
  <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/Browse.chunk.647087.css" rel="stylesheet"/>
  <title>
   Phone- Buy Products Online at Best Price in India - All Categories | Flipkart.com
  </title>
  <meta content="Phone- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="og_title" property="og:title">
   <meta content="Phone" name="Keywords">
    <meta content="Phone- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" name="Description">
     <meta content="Phone- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" property="og:description">
      <meta content="F4EEB3A0AFFDD385992A06E6920C0AC3" name="msvalidate.01">
       <!--[if IE 9 ]>
	<script nonce="18393894387124668698">
		window.browserVersion = 'IE9';
		document.documentElement.className += ' ie9';
	</script>
	<![endif]-->
       <!--[if !IE]><!-->
       <script nonce="18393894387124668698">
        if (/*@cc_on!@*/false) {
			window.browserVersion = 'IE10';
			document.documentElement.className += ' ie10';
		}
       </script>
       <!--<![endif]-->
       <script nonce="18393894387124668698">
        ;window.NREUM||(NREUM={});NREUM.init={distributed_tracing:{enabled:true},privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]}};

			;NREUM.loader_config={accountID:"3700282",trustKey:"3679896",agentID:"1588759528",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528"}
			;NREUM.info={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528",sa:1}

			;/*! For license information please see nr-loader-spa-1.236.0.min.js.LICENSE.txt */

In [67]:
name = soup.find('div', class_ = 'RG5Slk')
name

In [68]:
name.text

'vivo T5x 5G (Cyber Green, 128 GB)'

In [69]:
price = soup.find('div', class_ = 'hZ3P6w DeU9vF')
price.text

'₹22,999'

In [70]:
rating = soup.find('div', class_ = 'MKiFS6')
rating.text

'4.4'

In [71]:
ratings_reviews = soup.find('span', class_ = 'PvbNMB')
ratings_reviews.text

'5,888 Ratings\xa0&\xa0390 Reviews'

In [72]:
specifications = soup.find('div', class_ = 'CMXw7N')
specifications

<div class="CMXw7N"><ul class="HwRTzP"><li class="DTBslk">6 GB RAM | 128 GB ROM</li><li class="DTBslk">17.17 cm (6.76 inch) Display</li><li class="DTBslk">50MP + 2MP | 32MP Front Camera</li><li class="DTBslk">7200 mAh Li-ion Battery</li><li class="DTBslk">Dimensity 7400-Turbo Processor</li><li class="DTBslk">1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories</li></ul></div>

In [73]:
specs = specifications.find_all('li', class_ = 'DTBslk')
specs

[<li class="DTBslk">6 GB RAM | 128 GB ROM</li>,
 <li class="DTBslk">17.17 cm (6.76 inch) Display</li>,
 <li class="DTBslk">50MP + 2MP | 32MP Front Camera</li>,
 <li class="DTBslk">7200 mAh Li-ion Battery</li>,
 <li class="DTBslk">Dimensity 7400-Turbo Processor</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories</li>]

In [74]:
print(len(specs))
print(specs[0].text)
print(specs[1].text)
print(specs[2].text)
print(specs[3].text)
print(specs[4].text)
print(specs[5].text)

6
6 GB RAM | 128 GB ROM
17.17 cm (6.76 inch) Display
50MP + 2MP | 32MP Front Camera
7200 mAh Li-ion Battery
Dimensity 7400-Turbo Processor
1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories

In [75]:
# Extracting product details of all the products on the webpage
product_details = soup.find_all('div', class_ = 'ZFwe0M row')
print(len(product_details))
product_details

24

[<div class="ZFwe0M row"><div class="col col-7-12"><div class="t7gRps"><svg class="" height="18" width="62" xmlns="http://www.w3.org/2000/svg"><rect fill="white" height="18" width="62"></rect><path d="M5.82955 6.45455C5.77841 6.02273 5.57102 5.6875 5.20739 5.44886C4.84375 5.21023 4.39773 5.09091 3.86932 5.09091C3.48295 5.09091 3.14489 5.15341 2.85511 5.27841C2.56818 5.40341 2.34375 5.57528 2.18182 5.79403C2.02273 6.01278 1.94318 6.26136 1.94318 6.53977C1.94318 6.77273 1.99858 6.97301 2.10938 7.14062C2.22301 7.3054 2.3679 7.44318 2.54403 7.55398C2.72017 7.66193 2.90483 7.75142 3.09801 7.82244C3.29119 7.89062 3.46875 7.94602 3.63068 7.98864L4.51705 8.22727C4.74432 8.28693 4.99716 8.36932 5.27557 8.47443C5.55682 8.57955 5.82528 8.72301 6.08097 8.90483C6.33949 9.08381 6.55256 9.31392 6.72017 9.59517C6.88778 9.87642 6.97159 10.2216 6.97159 10.6307C6.97159 11.1023 6.84801 11.5284 6.60085 11.9091C6.35653 12.2898 5.99858 12.5923 5.52699 12.8168C5.05824 13.0412 4.48864 13.1534 3.81818 13.1534C3.19318 13.1534 2.65199 13.0526 2.1946 12.8509C1.74006 12.6491 1.3821 12.3679 1.12074 12.0071C0.862216 11.6463 0.715909 11.2273 0.681818 10.75H1.77273C1.80114 11.0795 1.91193 11.3523 2.10511 11.5682C2.30114 11.7812 2.5483 11.9403 2.84659 12.0455C3.14773 12.1477 3.47159 12.1989 3.81818 12.1989C4.22159 12.1989 4.58381 12.1335 4.90483 12.0028C5.22585 11.8693 5.48011 11.6847 5.66761 11.4489C5.85511 11.2102 5.94886 10.9318 5.94886 10.6136C5.94886 10.3239 5.8679 10.0881 5.70597 9.90625C5.54403 9.72443 5.33097 9.5767 5.06676 9.46307C4.80256 9.34943 4.51705 9.25 4.21023 9.16477L3.13636 8.85795C2.45455 8.66193 1.91477 8.3821 1.51705 8.01847C1.11932 7.65483 0.920455 7.17898 0.920455 6.59091C0.920455 6.10227 1.05256 5.67614 1.31676 5.3125C1.58381 4.94602 1.94176 4.66193 2.39062 4.46023C2.84233 4.25568 3.34659 4.15341 3.90341 4.15341C4.46591 4.15341 4.96591 4.25426 5.40341 4.45597C5.84091 4.65483 6.1875 4.92756 6.44318 5.27415C6.7017 5.62074 6.83807 6.0142 6.85227 6.45455H5.82955ZM8.5728 15.4545V6.45455H9.54439V7.49432H9.66371C9.73757 7.38068 9.83984 7.2358 9.97053 7.05966C10.104 6.88068 10.2944 6.72159 10.5415 6.58239C10.7915 6.44034 11.1296 6.36932 11.5558 6.36932C12.1069 6.36932 12.5927 6.5071 13.0131 6.78267C13.4336 7.05824 13.7617 7.44886 13.9975 7.95455C14.2333 8.46023 14.3512 9.05682 14.3512 9.74432C14.3512 10.4375 14.2333 11.0384 13.9975 11.5469C13.7617 12.0526 13.435 12.4446 13.0174 12.723C12.5998 12.9986 12.1183 13.1364 11.5728 13.1364C11.1523 13.1364 10.8157 13.0668 10.5629 12.9276C10.31 12.7855 10.1154 12.625 9.97905 12.446C9.84268 12.2642 9.73757 12.1136 9.66371 11.9943H9.57848V15.4545H8.5728ZM9.56143 9.72727C9.56143 10.2216 9.63388 10.6577 9.77876 11.0355C9.92365 11.4105 10.1353 11.7045 10.4137 11.9176C10.6921 12.1278 11.033 12.233 11.4364 12.233C11.8569 12.233 12.2077 12.1222 12.489 11.9006C12.7731 11.6761 12.9862 11.375 13.1282 10.9972C13.2731 10.6165 13.3455 10.1932 13.3455 9.72727C13.3455 9.26705 13.2745 8.85227 13.1325 8.48295C12.9933 8.1108 12.7816 7.81676 12.4975 7.60085C12.2163 7.3821 11.8626 7.27273 11.4364 7.27273C11.0273 7.27273 10.6836 7.37642 10.4052 7.58381C10.1268 7.78835 9.91655 8.07528 9.7745 8.4446C9.63246 8.81108 9.56143 9.23864 9.56143 9.72727ZM18.5444 13.1364C17.9535 13.1364 17.435 12.9957 16.989 12.7145C16.5458 12.4332 16.1992 12.0398 15.9492 11.5341C15.7021 11.0284 15.5785 10.4375 15.5785 9.76136C15.5785 9.07955 15.7021 8.48437 15.9492 7.97585C16.1992 7.46733 16.5458 7.07244 16.989 6.79119C17.435 6.50994 17.9535 6.36932 18.5444 6.36932C19.1353 6.36932 19.6523 6.50994 20.0955 6.79119C20.5415 7.07244 20.8881 7.46733 21.1353 7.97585C21.3853 8.48437 21.5103 9.07955 21.5103 9.76136C21.5103 10.4375 21.3853 11.0284 21.1353 11.5341C20.8881 12.0398 20.5415 12.4332 20.0955 12.7145C19.6523 12.9957 19.1353 13.1364 18.5444 13.1364ZM18.5444 12.233C18.9933 12.233 19.3626 12.1179 19.6523 11.8878C19.9421 11.6577 20.1566 11.3551 20.2958 10.9801C20.435 10.6051 20.5046 10.1989 20.5046 9.76136C20.5046 9.32386 20.435 8.91619 20.2958 8.53835C20.1566 8.16051 19.9421 7.85511 19.6523 7.62216C19.3626 7.3892 18.9933 7.27273 18.5444 7.27273C18.0955 7.27273 17.7262 7.3892 17.4364 7.62216C17.1467 7.85511 16.9322 8.16051 16.793 8.53835C16.6538 8.91619 16.5842 9.32386 16.5842 9.76136C16.5842 10.1989 16.6538 10.6051 16.793 10.9801C16.9322 11.3551 17.1467 11.6577 17.4364 11.8878C17.7262 12.1179 18.0955 12.233 18.5444 12.233ZM24.0511 9.0625V13H23.0455V6.45455H24.017V7.47727H24.1023C24.2557 7.14489 24.4886 6.87784 24.8011 6.67614C25.1136 6.47159 25.517 6.36932 26.0114 6.36932C26.4545 6.36932 26.8423 6.46023 27.1747 6.64205C27.5071 6.82102 27.7656 7.09375 27.9503 7.46023C28.1349 7.82386 28.2273 8.28409 28.2273 8.84091V13H27.2216V8.90909C27.2216 8.39489 27.0881 7.99432 26.821 7.70739C26.554 7.41761 26.1875 7.27273 25.7216 7.27273C25.4006 7.27273 25.1136 7.34233 24.8608 7.48153C24.6108 7.62074 24.4134 7.82386 24.2685 8.09091C24.1236 8.35795 24.0511 8.68182 24.0511 9.0625ZM34.7013 7.92045L33.7979 8.17614C33.7411 8.02557 33.6573 7.87926 33.5465 7.73722C33.4386 7.59233 33.2908 7.47301 33.1033 7.37926C32.9158 7.28551 32.6758 7.23864 32.3832 7.23864C31.9826 7.23864 31.6488 7.33097 31.3817 7.51562C31.1175 7.69744 30.9854 7.92898 30.9854 8.21023C30.9854 8.46023 31.0763 8.65767 31.2582 8.80256C31.44 8.94744 31.7241 9.06818 32.1104 9.16477L33.082 9.40341C33.6673 9.54545 34.1033 9.76278 34.3903 10.0554C34.6772 10.3452 34.8207 10.7187 34.8207 11.1761C34.8207 11.5511 34.7127 11.8864 34.4968 12.1818C34.2837 12.4773 33.9854 12.7102 33.6019 12.8807C33.2184 13.0511 32.7724 13.1364 32.2638 13.1364C31.5962 13.1364 31.0437 12.9915 30.6062 12.7017C30.1687 12.4119 29.8917 11.9886 29.7752 11.4318L30.7298 11.1932C30.8207 11.5455 30.9925 11.8097 31.2454 11.9858C31.5011 12.1619 31.8349 12.25 32.2468 12.25C32.7156 12.25 33.0877 12.1506 33.3633 11.9517C33.6417 11.75 33.7809 11.5085 33.7809 11.2273C33.7809 11 33.7013 10.8097 33.5423 10.6562C33.3832 10.5 33.1388 10.3835 32.8093 10.3068L31.7184 10.0511C31.119 9.90909 30.6786 9.68892 30.3974 9.39062C30.119 9.08949 29.9798 8.71307 29.9798 8.26136C29.9798 7.89205 30.0835 7.56534 30.2908 7.28125C30.5011 6.99716 30.7866 6.77415 31.1474 6.61222C31.511 6.45028 31.9229 6.36932 32.3832 6.36932C33.0309 6.36932 33.5394 6.51136 33.9087 6.79545C34.2809 7.07955 34.5451 7.45455 34.7013 7.92045ZM38.9936 13.1364C38.4027 13.1364 37.8842 12.9957 37.4382 12.7145C36.995 12.4332 36.6484 12.0398 36.3984 11.5341C36.1513 11.0284 36.0277 10.4375 36.0277 9.76136C36.0277 9.07955 36.1513 8.48437 36.3984 7.97585C36.6484 7.46733 36.995 7.07244 37.4382 6.79119C37.8842 6.50994 38.4027 6.36932 38.9936 6.36932C39.5845 6.36932 40.1016 6.50994 40.5447 6.79119C40.9908 7.07244 41.3374 7.46733 41.5845 7.97585C41.8345 8.48437 41.9595 9.07955 41.9595 9.76136C41.9595 10.4375 41.8345 11.0284 41.5845 11.5341C41.3374 12.0398 40.9908 12.4332 40.5447 12.7145C40.1016 12.9957 39.5845 13.1364 38.9936 13.1364ZM38.9936 12.233C39.4425 12.233 39.8118 12.1179 40.1016 11.8878C40.3913 11.6577 40.6058 11.3551 40.745 10.9801C40.8842 10.6051 40.9538 10.1989 40.9538 9.76136C40.9538 9.32386 40.8842 8.91619 40.745 8.53835C40.6058 8.16051 40.3913 7.85511 40.1016 7.62216C39.8118 7.3892 39.4425 7.27273 38.9936 7.27273C38.5447 7.27273 38.1754 7.3892 37.8857 7.62216C37.5959 7.85511 37.3814 8.16051 37.2422 8.53835C37.103 8.91619 37.0334 9.32386 37.0334 9.76136C37.0334 10.1989 37.103 10.6051 37.2422 10.9801C37.3814 11.3551 37.5959 11.6577 37.8857 11.8878C38.1754 12.1179 38.5447 12.233 38.9936 12.233ZM43.4947 13V6.45455H44.4663V7.44318H44.5344C44.6538 7.11932 44.8697 6.85653 45.1822 6.65483C45.4947 6.45312 45.8469 6.35227 46.239 6.35227C46.3129 6.35227 46.4052 6.35369 46.516 6.35653C46.6268 6.35937 46.7106 6.36364 46.7674 6.36932V7.39205C46.7333 7.38352 46.6552 7.37074 46.533 7.35369C46.4137 7.33381 46.2873 7.32386 46.1538 7.32386C45.8356 7.32386 45.5515 7.39062 45.3015 7.52415C45.0543 7.65483 44.8583 7.83665 44.7134 8.0696C44.5714 8.29972 44.5004 8.5625 44.5004 8.85795V13H43.4947ZM50.5046 13.1364C49.8739 13.1364 49.3299 12.9972 48.8725 12.7188C48.418 12.4375 48.0671 12.0455 47.82 11.5426C47.5756 11.0369 47.4535 10.4489 47.4535 9.77841C47.4535 9.10795 47.5756 8.51705 47.82 8.00568C48.0671 7.49148 48.4109 7.09091 48.8512 6.80398C49.2944 6.5142 49.8114 6.36932 50.4023 6.36932C50.7433 6.36932 51.0799 6.42614 51.4123 6.53977C51.7447 6.65341 52.0472 6.83807 52.32 7.09375C52.5927 7.34659 52.81 7.68182 52.9719 8.09943C53.1339 8.51705 53.2148 9.03125 53.2148 9.64205V10.0682H48.1694V9.19886H52.1921C52.1921 8.82955 52.1183 8.5 51.9705 8.21023C51.8256 7.92045 51.6183 7.69176 51.3484 7.52415C51.0813 7.35653 50.766 7.27273 50.4023 7.27273C50.0018 7.27273 49.6552 7.37216 49.3626 7.57102C49.0728 7.76705 48.8498 8.02273 48.6935 8.33807C48.5373 8.65341 48.4592 8.99148 48.4592 9.35227V9.93182C48.4592 10.4261 48.5444 10.8452 48.7148 11.1889C48.8881 11.5298 49.1282 11.7898 49.435 11.9688C49.7418 12.1449 50.0984 12.233 50.5046 12.233C50.7688 12.233 51.0075 12.196 51.2205 12.1222C51.4364 12.0455 51.6225 11.9318 51.7788 11.7812C51.935 11.6278 52.0558 11.4375 52.141 11.2102L53.1126 11.483C53.0103 11.8125 52.8384 12.1023 52.5969 12.3523C52.3555 12.5994 52.0572 12.7926 51.7021 12.9318C51.3469 13.0682 50.9478 13.1364 50.5046 13.1364ZM57.2163 13.1364C56.6708 13.1364 56.1893 12.9986 55.7717 12.723C55.354 12.4446 55.0273 12.0526 54.7915 11.5469C54.5558 11.0384 54.4379 10.4375 54.4379 9.74432C54.4379 9.05682 54.5558 8.46023 54.7915 7.95455C55.0273 7.44886 55.3555 7.05824 55.7759 6.78267C56.1964 6.5071 56.6822 6.36932 57.2333 6.36932C57.6594 6.36932 57.9961 6.44034 58.2433 6.58239C58.4933 6.72159 58.6836 6.88068 58.8143 7.05966C58.9478 7.2358 59.0515 7.38068 59.1254 7.49432H59.2106V4.27273H60.2163V13H59.2447V11.9943H59.1254C59.0515 12.1136 58.9464 12.2642 58.81 12.446C58.6737 12.625 58.479 12.7855 58.2262 12.9276C57.9734 13.0668 57.6367 13.1364 57.2163 13.1364ZM57.3526 12.233C57.756 12.233 58.0969 12.1278 58.3754 11.9176C58.6538 11.7045 58.8654 11.4105 59.0103 11.0355C59.1552 10.6577 59.2276 10.2216 59.2276 9.72727C59.2276 9.23864 59.1566 8.81108 59.0146 8.4446C58.8725 8.07528 58.6623 7.78835 58.3839 7.58381C58.1055 7.37642 57.7617 7.27273 57.3526 7.27273C56.9265 7.27273 56.5714 7.3821 56.2873 7.60085C56.006 7.81676 55.7944 8.1108 55.6523 8.48295C55.5131 8.85227 55.4435 9.26705 55.4435 9.72727C55.4435 10.1932 55.5146 10.6165 55.6566 10.9972C55.8015 11.375 56.0146 11.6761 56.2958 11.9006C56.5799 12.1222 56.9322 12.233 57.3526 12.233Z" fill="#9E9E9E"></path></svg></div><div class="RG5Slk">vivo T5x 5G (Cyber Green, 128 GB)</div><div class="a7saXW"><span class="CjyrHS" id="productRating_LSTMOBHH69NGFZAYK6MYQKNQD_MOBHH69NGFZAYK6M_"><div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span><span class="PvbNMB"><span><span>5,888 Ratings </span><span class="o2SIOJ">&amp;</span><span> 390 Reviews</span></span></span></div><div class="CMXw7N"><ul class="HwRTzP"><li class="DTBslk">6 GB RAM | 128 GB ROM</li><li class="DTBslk">17.17 cm (6.76 inch) Display</li><li class="DTBslk">50MP + 2MP | 32MP Front Camera</li><li class="DTBslk">7200 mAh Li-ion Battery</li><li class="DTBslk">Dimensity 7400-Turbo Processor</li><li class="DTBslk">1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories</li></ul></div></div><div class="col col-5-12 mao5dl"><div class="oFEPlD"><div class="QiMO5r"><div class="hZ3P6w DeU9vF">₹22,999</div><div class="kRYCnD gxR4EY">₹<!-- -->28,999</div><div class="HQe8jr"><span>20% off</span></div></div></div><div class="qYp2rh"><img height="21" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_9e47c1.png"/></div><div class="MaiFhH"><div class="hx1EGN"><div class="HZ0E6r Rm9_cy" style="color:#000000;font-size:14px;font-style:normal;font-weight:400">Upto </div><div class="HZ0E6r Rm9_cy" style="color:#000000;font-size:14px;font-style:normal;font-weight:700">₹16,350</div><div class="HZ0E6r Rm9_cy" style="color:#000000;font-size:14px;font-style:normal;font-weight:400"> Off on Exchange</div></div></div><div class="MaiFhH"><div class="hx1EGN"><div class="HZ0E6r Rm9_cy" style="color:#26A541;font-size:14px;font-weight:700">Bank Offer</div></div></div></div></div>,
 <div class="ZFwe0M row"><div class="col col-7-12"><div class="RG5Slk">IQOO Z11x 5G (Prismatic Green, 128 GB)</div><div class="a7saXW"><span class="CjyrHS" id="productRating_LSTMOBHHHBTCWXSUNG5TW8KCJ_MOBHHHBTCWXSUNG5_"><div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span><span class="PvbNMB"><span><span>430 Ratings </span><span class="o2SIOJ">&amp;</span><span> 38 Reviews</span></span></span></div><div class="CMXw7N"><ul class="HwRTzP"><li class="DTBslk">6 GB RAM | 128 GB ROM</li><li class="DTBslk">17.02 cm (6.7 inch) Display</li><li class="DTBslk">50MP Rear Camera</li><li class="DTBslk">7200 mAh Battery</li><li class="DTBslk">12 Months Brand Warranty</li></ul></div></div><div class="col col-5-12 mao5dl"><div class="oFEPlD"><div class="QiMO5r"><div class="hZ3P6w DeU9vF">₹21,745</div><div class="kRYCnD gxR4EY">₹<!-- -->28,999</div><div class="HQe8jr"><span>25% off</span></div></div></div><div class="qYp2rh"><img height="21" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_9e47c1.png"/></div><div class="MaiFhH"><div class="hx1EGN" style="padding-top:4px;padding-right:4px;padding-bottom:4px;padding-left:4px;border-radius:2px;background-color:#F4F2FF"><div class="HZ0E6r Rm9_cy" style="color:#5209DB;font-size:12px;font-style:normal;font-weight:500">SALE PE SALE</div></div></div><div class="MaiFhH"><div class="hx1EGN"><div class="HZ0E6r Rm9_cy" style="color:#C70055;font-size:12px;font-weight:700">Only few left</div></div></div></div></div>,
 <div class="ZFwe0M row"><div class="col col-7-12"><div class="RG5Slk">POCO M8 Charger in the Box (Frost Silver, 256 GB)</div><div class="a7saXW"><span class="CjyrHS" id="productRating_LSTMOBHMGG52VFGBGZEZEW7SR_MOBHMGG52VFGBGZE_"><div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span><span class="PvbNMB"><span><span>1,106 Ratings </span><span class="o2SIOJ">&amp;</span><span> 105 Reviews</span></span></span></div><div class="CMXw7N"><ul class="HwRTzP"><li class="DTBslk">8 GB RAM | 256 GB ROM | Expandable Upto 1 TB</li><li class="DTBslk">17.2 cm (6.77 inch) Full HD+ Display</li><li class="DTBslk">50MP Rear Camera | 20MP Front Camera</li><li class="DTBslk">5520 mAh Battery</li><li class="DTBslk">1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories</li></ul></div></div><div class="col col-5-12 mao5dl"><div class="oFEPlD"><div class="QiMO5r"><div class="hZ3P6w DeU9vF">₹21,499</div><div class="kRYCnD gxR4EY">₹<!-- -->29,999</div><div class="HQe8jr"><span>28% off</span></div></div></div><div class="qYp2rh"><img height="21" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_9e47c1.png"/></div><div class="MaiFhH"><div class="hx1EGN"><div class="HZ0E6r Rm9_cy" style="color:#000000;font-size:14px;font-style:normal;font-weight:400">Upto </div><div class="HZ0E6r Rm9_cy" style="color:#000000;font-size:14px;font-style:normal;font-weight:700">₹15,300</div><div class="HZ0E6r Rm9_cy" style="color:#000000;font-size:14px;font-style:normal;font-weight:400"> Off on Exchange</div></div></div><div class="MaiFhH"><div class="hx1EGN"><div class="HZ0E6r Rm9_cy" style="color:#26A541;font-size:14px;font-weight:700">Bank Offer</div></div></div></div></div>,
 <div class="ZFwe0M row"><div class="col col-7-12"><div class="RG5Slk">MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream, 128 GB)</div><div class="a7saXW"><span class="CjyrHS" id="productRating_LSTMOBHHD2K5N9G9VJYMQ1MCU_MOBHHD2K5N9G9VJY_"><div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span><span class="PvbNMB"><span><span>1,17,291 Ratings </span><span class="o2SIOJ">&amp;</span><span> 6,844 Reviews</span></span></span></div><div class="CMXw7N"><ul class="HwRTzP"><li class="DTBslk">8 GB RAM | 128 GB ROM | Expandable Upto 1 TB</li><li class="DTBslk">16.94 cm (6.67 inch) Display</li><li class="DTBslk">50MP + 13MP | 32MP Front Camera</li><li class="DTBslk">5500 mAh Battery</li><li class="DTBslk">Dimensity 7400 Processor</li><li class="DTBslk">68W Charger</li><li class="DTBslk">1 Year Warranty on Handset and 6 Months Warranty on Accessories</li></ul></div></div><div class="col col-5-12 mao5dl"><div class="oFEPlD"><div class="QiMO5r"><div class="hZ3P6w DeU9vF">₹20,999</div><div class="kRYCnD gxR4EY">₹<!-- -->24,999</div><div class="HQe8jr"><span>16% off</span></div></div></div><div class="qYp2rh"><img height="21" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_9e47c1.png"/></div><div class="MaiFhH"><div class="hx1EGN"><div class="HZ0E6r Rm9_cy" style="color:#000000;font-size:14px;font-style:normal;font-weight:400">Upto </div><div class="HZ0E6r Rm9_cy" style="color:#000000;font-size:14px;font-style:normal;font-weight:700">₹14,500</div><div class="HZ0E6r Rm9_cy" style="color:#000000;font-size:14px;font-style:normal;font-weight:400"> Off on Exchange</div></div></div><div class="MaiFhH"><div class="hx1EGN"><div class="HZ0E6r Rm9_cy" style="color:#26A541;font-size:14px;font-weight:700">Bank Offer</div></div></div></div></div>,

In [76]:
# Showing product details one by one
for product in product_details:
    # name
    name = product.find('div', class_ = 'RG5Slk')
    if name is None:
        print('Name not available')
    else:
        print(name.text)
        
    # price
    price = product.find('div', class_ = 'hZ3P6w DeU9vF')
    if price is None:
        print('Price not available')
    else:
        print(price.text)
        
    # rating
    rating = product.find('div', class_ = 'MKiFS6')
    if rating is None:
        print('Rating not available')
    else:
        print(rating.text)
        
    # ratings and reviews
    ratings_reviews = product.find('span', class_ = 'PvbNMB')
    if ratings_reviews is None:
        print('Number of Ratings and reviews not available')
    else:
        print(ratings_reviews.text)
        
    # specifications
    features = []
    specifications = product.find('div', class_ = 'CMXw7N')
    specs = specifications.find_all('li', class_ = 'DTBslk')
    for feature in specs:
        features.append(feature.text)
    print(features)
    
    print('=' * 100)
    print()

vivo T5x 5G (Cyber Green, 128 GB)
₹22,999
4.4
5,888 Ratings & 390 Reviews
['6 GB RAM | 128 GB ROM', '17.17 cm (6.76 inch) Display', '50MP + 2MP | 32MP Front Camera', '7200 mAh Li-ion Battery', 'Dimensity 7400-Turbo Processor', '1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories']
====================================================================================================

IQOO Z11x 5G (Prismatic Green, 128 GB)
₹21,745
4.4
430 Ratings & 38 Reviews
['6 GB RAM | 128 GB ROM', '17.02 cm (6.7 inch) Display', '50MP Rear Camera', '7200 mAh Battery', '12 Months Brand Warranty']
====================================================================================================

POCO M8 Charger in the Box (Frost Silver, 256 GB)
₹21,499
4.4
1,106 Ratings & 105 Reviews
['8 GB RAM | 256 GB ROM | Expandable Upto 1 TB', '17.2 cm (6.77 inch) Full HD+ Display', '50MP Rear Camera | 20MP Front Camera', '5520 mAh Battery', '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories']
====================================================================================================

MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream, 128 GB)
₹20,999
4.4
1,17,291 Ratings & 6,844 Reviews
['8 GB RAM | 128 GB ROM | Expandable Upto 1 TB', '16.94 cm (6.67 inch) Display', '50MP + 13MP | 32MP Front Camera', '5500 mAh Battery', 'Dimensity 7400 Processor', '68W Charger', '1 Year Warranty on Handset and 6 Months Warranty on Accessories']
====================================================================================================

vivo X200T (Stellar Black, 256 GB)
₹59,999
4.6
2,173 Ratings & 376 Reviews
['12 GB RAM | 256 GB ROM', '16.94 cm (6.67 inch) Full HD+ AMOLED Display', '50MP + 50MP + 50MP | 32MP Front Camera', '6200 mAh Battery', 'Dimensity 9400+ Processor', '1 Year Warranty on Handset and 6 Months Warranty on Accessories']
====================================================================================================

MOTOROLA Edge 60 Fusion 5G (PANTONE Amazonite, 128 GB)
₹20,999
4.4
1,17,291 Ratings & 6,844 Reviews
['8 GB RAM | 128 GB ROM | Expandable Upto 1 TB', '16.94 cm (6.67 inch) Display', '50MP + 13MP | 32MP Front Camera', '5500 mAh Battery', 'Dimensity 7400 Processor', '68W Charger', '1 Year Warranty on Handset and 6 Months Warranty on Accessories']
====================================================================================================

MOTOROLA Edge 60 Fusion 5G (PANTONE Zephyr, 128 GB)
₹20,999
4.4
1,17,291 Ratings & 6,844 Reviews
['8 GB RAM | 128 GB ROM | Expandable Upto 1 TB', '16.94 cm (6.67 inch) Display', '50MP + 13MP | 32MP Front Camera', '5500 mAh Battery', 'Dimensity 7400 Processor', '68W Charger', '1 Year Warranty on Handset and 6 Months Warranty on Accessories']
====================================================================================================

realme P4x 5G (Matte Silver, 256 GB)
₹20,999
4.3
4,649 Ratings & 347 Reviews
['8 GB RAM | 256 GB ROM', '17.07 cm (6.72 inch) Full HD+ Display', '50MP + 2MP | 8MP Front Camera', '7000 mAh Battery', 'Dimensity 7400 Ultra Processor', '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In-Box Accessories']
====================================================================================================

Ai+ NovaFlip 5G (Glacier White, 256 GB)
₹39,999
4.2
6 Ratings & 1 Reviews
['8 GB RAM | 256 GB ROM', '17.53 cm (6.9 inch) Full HD+ AMOLED Display', '50MP + 2MP | 32MP Front Camera', '4325 mAh Battery', '1 Year Warranty on Handset and 6 Months Warranty on the Inbox Accessories']
====================================================================================================

Samsung Galaxy S25 FE 5G (Navy, 256 GB)
₹50,999
4.6
621 Ratings & 61 Reviews
['8 GB RAM | 256 GB ROM', '17.02 cm (6.7 inch) Full HD+ Display', '50MP + 12MP + 8MP | 12MP Front Camera', '4900 mAh Li-ion Battery', 'Exynos 2400 Processor', '1 Year Manufacturer Warranty for Device and 6 Months for In-Box Accessories']
====================================================================================================

Nothing Phone (4a) (White, 256 GB)
₹37,999
4.4
3,699 Ratings & 395 Reviews
['8 GB RAM | 256 GB ROM', '17.22 cm (6.78 inch) Full HD+ AMOLED Display', '50MP + 50MP + 8MP | 32MP Front Camera', '5400 mAh Lithium ion Battery', 'Snapdragon 7s Gen 4 Processor', '1 Year Manufacturing Warranty']
====================================================================================================

vivo X200T (Seaside Lilac, 512 GB)
₹69,999
4.6
2,173 Ratings & 376 Reviews
['12 GB RAM | 512 GB ROM', '16.94 cm (6.67 inch) Full HD+ AMOLED Display', '50MP + 50MP + 50MP | 32MP Front Camera', '6200 mAh Battery', 'Dimensity 9400+ Processor', '1 Year Warranty on Handset and 6 Months Warranty on Accessories']
====================================================================================================

MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream, 256 GB)
₹26,999
4.4
44,289 Ratings & 2,600 Reviews
['12 GB RAM | 256 GB ROM | Expandable Upto 1 TB', '16.94 cm (6.67 inch) Display', '50MP + 13MP | 32MP Front Camera', '5500 mAh Battery', 'Dimensity 7400 Processor', '68W Charger', '1 Year Warranty on Handset and 6 Months Warranty on Accessories']
====================================================================================================

realme P4 5G (Steel Grey, 128 GB)
₹19,999
4.4
20,916 Ratings & 1,391 Reviews
['6 GB RAM | 128 GB ROM', '17.2 cm (6.77 inch) Display', '50MP + 8MP | 16MP Front Camera', '7000 mAh Battery', 'Mediatek Dimensity 7400 Processor', '1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories']
====================================================================================================

vivo X200T (Seaside Lilac, 256 GB)
₹59,999
4.6
2,173 Ratings & 376 Reviews
['12 GB RAM | 256 GB ROM', '16.94 cm (6.67 inch) Full HD+ AMOLED Display', '50MP + 50MP + 50MP | 32MP Front Camera', '6200 mAh Battery', 'Dimensity 9400+ Processor', '1 Year Warranty on Handset and 6 Months Warranty on Accessories']
====================================================================================================

realme 15 Pro 5G (Velvet Green, 256 GB)
₹28,999
4.3
9,289 Ratings & 828 Reviews
['8 GB RAM | 256 GB ROM', '17.27 cm (6.8 inch) Display', '50MP + 50MP | 50MP Front Camera', '7000 mAh Battery', 'Snapdragon 7 Gen 4 Processor', '1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories']
====================================================================================================

Samsung Galaxy S25 FE 5G (Jetblack, 256 GB)
₹50,999
4.6
621 Ratings & 61 Reviews
['8 GB RAM | 256 GB ROM', '17.02 cm (6.7 inch) Full HD+ Display', '50MP + 12MP + 8MP | 12MP Front Camera', '4900 mAh Li-ion Battery', 'Exynos 2400 Processor', '1 Year Manufacturer Warranty for Device and 6 Months for In-Box Accessories']
====================================================================================================

IQOO Z11x 5G (Prismatic Green, 128 GB)
₹23,810
4.4
632 Ratings & 54 Reviews
['8 GB RAM | 128 GB ROM', '17.02 cm (6.7 inch) Display', '50MP Rear Camera', '7200 mAh Battery', '12 Months Brand Warranty']
====================================================================================================

realme 15 Pro 5G (Flowing Silver, 512 GB)
₹32,999
4.4
5,465 Ratings & 417 Reviews
['12 GB RAM | 512 GB ROM', '17.27 cm (6.8 inch) Display', '50MP + 50MP | 50MP Front Camera', '7000 mAh Battery', 'Snapdragon 7 Gen 4 Processor', '1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories']
====================================================================================================

Samsung Galaxy S25 5G (Silver Shadow, 128 GB)
₹56,999
4.6
3,066 Ratings & 356 Reviews
['12 GB RAM | 128 GB ROM', '15.75 cm (6.2 inch) Full HD+ Display', '50MP + 10MP + 12MP | 12MP Front Camera', '4000 mAh Battery', '8 Elite for Galaxy Processor', '1 Year Manufacturer Warranty for Device and 6 Months for In-Box Accessories']
====================================================================================================

IQOO Z11x 5G (Titan Black, 128 GB)
₹23,580
4.4
632 Ratings & 54 Reviews
['8 GB RAM | 128 GB ROM', '17.02 cm (6.7 inch) Display', '50MP Rear Camera', '7200 mAh Battery', '12 Months Brand Warranty']
====================================================================================================

realme P4 Power 5G (TransOrange, 256 GB)
₹27,999
4.5
4,007 Ratings & 358 Reviews
['8 GB RAM | 256 GB ROM', '17.27 cm (6.8 inch) Full HD+ AMOLED Display', '50MP + 8MP | Yes', '10001 mAh Battery', 'Dimensity 7400 Ultra Processor', '1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories']
====================================================================================================

Apple iPhone 17 (Black, 256 GB)
₹78,900
4.6
10,389 Ratings & 628 Reviews
['256 GB ROM', '16.0 cm (6.3 inch) Super Retina XDR Display', '48MP + 48MP | 18MP Front Camera', 'A19 Chip, 6 Core Processor Processor', 'Apple One (1) Year Limited Warranty']
====================================================================================================

REDMI Note 15 SE 5G (Crimson Reserve, 128 GB)
₹21,999
4.3
587 Ratings & 70 Reviews
['8 GB RAM | 128 GB ROM | Expandable Upto 1 TB', '17.2 cm (6.77 inch) Full HD+ AMOLED Display', '50MP Rear Camera | 20MP Front Camera', '5800 mAh Lithium-Ion Polymer Battery', 'Snapdragon 6 Gen 3 Processor', '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories']
====================================================================================================

In [77]:
# Storing information in lists
titles = []
prices = []
ratings = []
RnR = []
features = []

# Extracting product details of all products on the webpage
product_details = soup.find_all('div', class_ = 'ZFwe0M row')

for product in product_details:
    # name
    name = product.find('div', class_ = 'RG5Slk')
    if name is None:
        titles.append(np.nan)
    else:
        titles.append(name.text)
        
    # price
    price = product.find('div', class_ = 'hZ3P6w DeU9vF')
    if price is None:
        prices.append(np.nan)
    else:
        prices.append(price.text)
        
    # rating
    rating = product.find('div', class_ = 'MKiFS6')
    if rating is None:
        ratings.append(np.nan)
    else:
        ratings.append(rating.text)
        
    # ratings and reviews
    ratings_reviews = product.find('span', class_ = 'PvbNMB')
    if ratings_reviews is None:
        RnR.append(np.nan)
    else:
        RnR.append(ratings_reviews.text)
        
    # specifications
    f = []
    specifications = product.find('div', class_ = 'CMXw7N')
    specs = specifications.find_all('li', class_ = 'DTBslk')
    for feature in specs:
        f.append(feature.text)
    features.append(f)

In [78]:
print(len(titles))
print(len(prices))
print(len(ratings))
print(len(RnR))
print(len(features))

24
24
24
24
24

In [79]:
print(titles)
print()
print(prices)
print()
print(ratings)
print()
print(RnR)

['vivo T5x 5G (Cyber Green, 128 GB)', 'IQOO Z11x 5G (Prismatic Green, 128 GB)', 'POCO M8 Charger in the Box (Frost Silver, 256 GB)', 'MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream, 128 GB)', 'vivo X200T (Stellar Black, 256 GB)', 'MOTOROLA Edge 60 Fusion 5G (PANTONE Amazonite, 128 GB)', 'MOTOROLA Edge 60 Fusion 5G (PANTONE Zephyr, 128 GB)', 'realme P4x 5G (Matte Silver, 256 GB)', 'Ai+ NovaFlip 5G (Glacier White, 256 GB)', 'Samsung Galaxy S25 FE 5G (Navy, 256 GB)', 'Nothing Phone (4a) (White, 256 GB)', 'vivo X200T (Seaside Lilac, 512 GB)', 'MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream, 256 GB)', 'realme P4 5G (Steel Grey, 128 GB)', 'vivo X200T (Seaside Lilac, 256 GB)', 'realme 15 Pro 5G (Velvet Green, 256 GB)', 'Samsung Galaxy S25 FE 5G (Jetblack, 256 GB)', 'IQOO Z11x 5G (Prismatic Green, 128 GB)', 'realme 15 Pro 5G (Flowing Silver, 512 GB)', 'Samsung Galaxy S25 5G (Silver Shadow, 128 GB)', 'IQOO Z11x 5G (Titan Black, 128 GB)', 'realme P4 Power 5G (TransOrange, 256 GB)', 'Apple iPhone 17 (Black, 256 GB)', 'REDMI Note 15 SE 5G (Crimson Reserve, 128 GB)']

['₹22,999', '₹21,745', '₹21,499', '₹20,999', '₹59,999', '₹20,999', '₹20,999', '₹20,999', '₹39,999', '₹50,999', '₹37,999', '₹69,999', '₹26,999', '₹19,999', '₹59,999', '₹28,999', '₹50,999', '₹23,810', '₹32,999', '₹56,999', '₹23,580', '₹27,999', '₹78,900', '₹21,999']

['4.4', '4.4', '4.4', '4.4', '4.6', '4.4', '4.4', '4.3', '4.2', '4.6', '4.4', '4.6', '4.4', '4.4', '4.6', '4.3', '4.6', '4.4', '4.4', '4.6', '4.4', '4.5', '4.6', '4.3']

['5,888 Ratings\xa0&\xa0390 Reviews', '430 Ratings\xa0&\xa038 Reviews', '1,106 Ratings\xa0&\xa0105 Reviews', '1,17,291 Ratings\xa0&\xa06,844 Reviews', '2,173 Ratings\xa0&\xa0376 Reviews', '1,17,291 Ratings\xa0&\xa06,844 Reviews', '1,17,291 Ratings\xa0&\xa06,844 Reviews', '4,649 Ratings\xa0&\xa0347 Reviews', '6 Ratings\xa0&\xa01 Reviews', '621 Ratings\xa0&\xa061 Reviews', '3,699 Ratings\xa0&\xa0395 Reviews', '2,173 Ratings\xa0&\xa0376 Reviews', '44,289 Ratings\xa0&\xa02,600 Reviews', '20,916 Ratings\xa0&\xa01,391 Reviews', '2,173 Ratings\xa0&\xa0376 Reviews', '9,289 Ratings\xa0&\xa0828 Reviews', '621 Ratings\xa0&\xa061 Reviews', '632 Ratings\xa0&\xa054 Reviews', '5,465 Ratings\xa0&\xa0417 Reviews', '3,066 Ratings\xa0&\xa0356 Reviews', '632 Ratings\xa0&\xa054 Reviews', '4,007 Ratings\xa0&\xa0358 Reviews', '10,389 Ratings\xa0&\xa0628 Reviews', '587 Ratings\xa0&\xa070 Reviews']

In [80]:
features

[['6 GB RAM | 128 GB ROM',
  '17.17 cm (6.76 inch) Display',
  '50MP + 2MP | 32MP Front Camera',
  '7200 mAh Li-ion Battery',
  'Dimensity 7400-Turbo Processor',
  '1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories'],
 ['6 GB RAM | 128 GB ROM',
  '17.02 cm (6.7 inch) Display',
  '50MP Rear Camera',
  '7200 mAh Battery',
  '12 Months Brand Warranty'],
 ['8 GB RAM | 256 GB ROM | Expandable Upto 1 TB',
  '17.2 cm (6.77 inch) Full HD+ Display',
  '50MP Rear Camera | 20MP Front Camera',
  '5520 mAh Battery',
  '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories'],
 ['8 GB RAM | 128 GB ROM | Expandable Upto 1 TB',
  '16.94 cm (6.67 inch) Display',
  '50MP + 13MP | 32MP Front Camera',
  '5500 mAh Battery',
  'Dimensity 7400 Processor',
  '68W Charger',
  '1 Year Warranty on Handset and 6 Months Warranty on Accessories'],
 ['12 GB RAM | 256 GB ROM',
  '16.94 cm (6.67 inch) Full HD+ AMOLED Display',
  '50MP + 50MP + 50MP | 32MP Front Camera',
  '6200 mAh Battery',
  'Dimensity 9400+ Processor',
  '1 Year Warranty on Handset and 6 Months Warranty on Accessories'],
 ['8 GB RAM | 128 GB ROM | Expandable Upto 1 TB',
  '16.94 cm (6.67 inch) Display',
  '50MP + 13MP | 32MP Front Camera',
  '5500 mAh Battery',
  'Dimensity 7400 Processor',
  '68W Charger',
  '1 Year Warranty on Handset and 6 Months Warranty on Accessories'],
 ['8 GB RAM | 128 GB ROM | Expandable Upto 1 TB',
  '16.94 cm (6.67 inch) Display',
  '50MP + 13MP | 32MP Front Camera',
  '5500 mAh Battery',
  'Dimensity 7400 Processor',
  '68W Charger',
  '1 Year Warranty on Handset and 6 Months Warranty on Accessories'],
 ['8 GB RAM | 256 GB ROM',
  '17.07 cm (6.72 inch) Full HD+ Display',
  '50MP + 2MP | 8MP Front Camera',
  '7000 mAh Battery',
  'Dimensity 7400 Ultra Processor',
  '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In-Box Accessories'],
 ['8 GB RAM | 256 GB ROM',
  '17.53 cm (6.9 inch) Full HD+ AMOLED Display',
  '50MP + 2MP | 32MP Front Camera',
  '4325 mAh Battery',
  '1 Year Warranty on Handset and 6 Months Warranty on the Inbox Accessories'],
 ['8 GB RAM | 256 GB ROM',
  '17.02 cm (6.7 inch) Full HD+ Display',
  '50MP + 12MP + 8MP | 12MP Front Camera',
  '4900 mAh Li-ion Battery',
  'Exynos 2400 Processor',
  '1 Year Manufacturer Warranty for Device and 6 Months for In-Box Accessories'],
 ['8 GB RAM | 256 GB ROM',
  '17.22 cm (6.78 inch) Full HD+ AMOLED Display',
  '50MP + 50MP + 8MP | 32MP Front Camera',
  '5400 mAh Lithium ion Battery',
  'Snapdragon 7s Gen 4 Processor',
  '1 Year Manufacturing Warranty'],
 ['12 GB RAM | 512 GB ROM',
  '16.94 cm (6.67 inch) Full HD+ AMOLED Display',
  '50MP + 50MP + 50MP | 32MP Front Camera',
  '6200 mAh Battery',
  'Dimensity 9400+ Processor',
  '1 Year Warranty on Handset and 6 Months Warranty on Accessories'],
 ['12 GB RAM | 256 GB ROM | Expandable Upto 1 TB',
  '16.94 cm (6.67 inch) Display',
  '50MP + 13MP | 32MP Front Camera',
  '5500 mAh Battery',
  'Dimensity 7400 Processor',
  '68W Charger',
  '1 Year Warranty on Handset and 6 Months Warranty on Accessories'],
 ['6 GB RAM | 128 GB ROM',
  '17.2 cm (6.77 inch) Display',
  '50MP + 8MP | 16MP Front Camera',
  '7000 mAh Battery',
  'Mediatek Dimensity 7400 Processor',
  '1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories'],
 ['12 GB RAM | 256 GB ROM',
  '16.94 cm (6.67 inch) Full HD+ AMOLED Display',
  '50MP + 50MP + 50MP | 32MP Front Camera',
  '6200 mAh Battery',
  'Dimensity 9400+ Processor',
  '1 Year Warranty on Handset and 6 Months Warranty on Accessories'],
 ['8 GB RAM | 256 GB ROM',
  '17.27 cm (6.8 inch) Display',
  '50MP + 50MP | 50MP Front Camera',
  '7000 mAh Battery',
  'Snapdragon 7 Gen 4 Processor',
  '1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories'],
 ['8 GB RAM | 256 GB ROM',
  '17.02 cm (6.7 inch) Full HD+ Display',
  '50MP + 12MP + 8MP | 12MP Front Camera',
  '4900 mAh Li-ion Battery',
  'Exynos 2400 Processor',
  '1 Year Manufacturer Warranty for Device and 6 Months for In-Box Accessories'],
 ['8 GB RAM | 128 GB ROM',
  '17.02 cm (6.7 inch) Display',
  '50MP Rear Camera',
  '7200 mAh Battery',
  '12 Months Brand Warranty'],
 ['12 GB RAM | 512 GB ROM',
  '17.27 cm (6.8 inch) Display',
  '50MP + 50MP | 50MP Front Camera',
  '7000 mAh Battery',
  'Snapdragon 7 Gen 4 Processor',
  '1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories'],
 ['12 GB RAM | 128 GB ROM',
  '15.75 cm (6.2 inch) Full HD+ Display',
  '50MP + 10MP + 12MP | 12MP Front Camera',
  '4000 mAh Battery',
  '8 Elite for Galaxy Processor',
  '1 Year Manufacturer Warranty for Device and 6 Months for In-Box Accessories'],
 ['8 GB RAM | 128 GB ROM',
  '17.02 cm (6.7 inch) Display',
  '50MP Rear Camera',
  '7200 mAh Battery',
  '12 Months Brand Warranty'],
 ['8 GB RAM | 256 GB ROM',
  '17.27 cm (6.8 inch) Full HD+ AMOLED Display',
  '50MP + 8MP | Yes',
  '10001 mAh Battery',
  'Dimensity 7400 Ultra Processor',
  '1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories'],
 ['256 GB ROM',
  '16.0 cm (6.3 inch) Super Retina XDR Display',
  '48MP + 48MP | 18MP Front Camera',
  'A19 Chip, 6 Core Processor Processor',
  'Apple One (1) Year Limited Warranty'],
 ['8 GB RAM | 128 GB ROM | Expandable Upto 1 TB',
  '17.2 cm (6.77 inch) Full HD+ AMOLED Display',
  '50MP Rear Camera | 20MP Front Camera',
  '5800 mAh Lithium-Ion Polymer Battery',
  'Snapdragon 6 Gen 3 Processor',
  '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories']]

In [81]:
# Storing information in lists
titles = []
prices = []
ratings = []
RnR = []
features = []
pgno = []

# loop to go through webpages
for x in range(1,11):
    start_time = time.time()
    
    URL = 'https://www.flipkart.com/search?q=phone&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&p%5B%5D=facets.price_range.from%3D20000&p%5B%5D=facets.price_range.to%3DMax&page={}'.format(x)
    
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36"
    }
    
    page = requests.get(URL, headers=headers)
    soup = BeautifulSoup(page.content, 'html.parser')
    
    # Extracting product details of all products on the webpage
    product_details = soup.find_all('div', class_ = 'ZFwe0M row')

    for product in product_details:
        # name
        name = product.find('div', class_ = 'RG5Slk')

        if name is None:
            titles.append(np.nan)
        else:
            titles.append(name.text)

        # price
        price = product.find('div', class_ = 'hZ3P6w DeU9vF')
        if price is None:
            prices.append(np.nan)
        else:
            prices.append(price.text)

        # rating
        rating = product.find('div', class_ = 'MKiFS6')
        if rating is None:
            ratings.append(np.nan)
        else:
            ratings.append(rating.text)

        # ratings and reviews
        ratings_reviews = product.find('span', class_ = 'PvbNMB')
        if ratings_reviews is None:
            RnR.append(np.nan)
        else:
            RnR.append(ratings_reviews.text)

        # specifications
        f = []
        specifications = product.find('div', class_ = 'CMXw7N')
        specs = specifications.find_all('li', class_ = 'DTBslk')
        for feature in specs:
            f.append(feature.text)
        features.append(f)
        
        # page number
        pgno.append(x)
        
    end_time = time.time()
    print('Page {} completed in {} seconds'.format(x, end_time - start_time))

Page 1 completed in 13.233106851577759 seconds
Page 2 completed in 2.39634370803833 seconds
Page 3 completed in 3.478250026702881 seconds
Page 4 completed in 0.7958965301513672 seconds
Page 5 completed in 0.7774219512939453 seconds
Page 6 completed in 0.6517009735107422 seconds
Page 7 completed in 0.745225191116333 seconds
Page 8 completed in 0.7082936763763428 seconds
Page 9 completed in 0.7334237098693848 seconds
Page 10 completed in 9.851868867874146 seconds

In [82]:
print(len(titles))
print(len(prices))
print(len(ratings))
print(len(RnR))
print(len(features))

240
240
240
240
240

In [83]:
data = {'Product_name' : titles,
        'Price'        : prices,
        'Rating'       : ratings,
        'No_of_RnR'    : RnR,
        'Features'     : features,
        'PageNo'       : pgno}

df = pd.DataFrame(data)
df.head(10)

,Product_name,Price,Rating,No_of_RnR,Features,PageNo
0,"vivo T5x 5G (Cyber Green, 128 GB)","₹22,999",4.4,"5,888 Ratings & 390 Reviews","[6 GB RAM | 128 GB ROM, 17.17 cm (6.76 inch) D...",1
1,"IQOO Z11x 5G (Prismatic Green, 128 GB)","₹21,745",4.4,430 Ratings & 38 Reviews,"[6 GB RAM | 128 GB ROM, 17.02 cm (6.7 inch) Di...",1
2,"POCO M8 Charger in the Box (Frost Silver, 256 GB)","₹21,499",4.4,"1,106 Ratings & 105 Reviews","[8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,...",1
3,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,"₹20,999",4.4,"1,17,291 Ratings & 6,844 Reviews","[8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,...",1
4,"vivo X200T (Stellar Black, 256 GB)","₹59,999",4.6,"2,173 Ratings & 376 Reviews","[12 GB RAM | 256 GB ROM, 16.94 cm (6.67 inch) ...",1
5,"MOTOROLA Edge 60 Fusion 5G (PANTONE Amazonite,...","₹20,999",4.4,"1,17,291 Ratings & 6,844 Reviews","[8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,...",1
6,"MOTOROLA Edge 60 Fusion 5G (PANTONE Zephyr, 12...","₹20,999",4.4,"1,17,291 Ratings & 6,844 Reviews","[8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,...",1
7,"realme P4x 5G (Matte Silver, 256 GB)","₹20,999",4.3,"4,649 Ratings & 347 Reviews","[8 GB RAM | 256 GB ROM, 17.07 cm (6.72 inch) F...",1
8,"Ai+ NovaFlip 5G (Glacier White, 256 GB)","₹39,999",4.2,6 Ratings & 1 Reviews,"[8 GB RAM | 256 GB ROM, 17.53 cm (6.9 inch) Fu...",1
9,"Samsung Galaxy S25 FE 5G (Navy, 256 GB)","₹50,999",4.6,621 Ratings & 61 Reviews,"[8 GB RAM | 256 GB ROM, 17.02 cm (6.7 inch) Fu...",1

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_name  240 non-null    object
 1   Price         240 non-null    object
 2   Rating        240 non-null    object
 3   No_of_RnR     240 non-null    object
 4   Features      240 non-null    object
 5   PageNo        240 non-null    int64
dtypes: int64(1), object(5)
memory usage: 11.4+ KB

In [85]:
# Converting price and rating to float
df.Rating = df.Rating.astype(float)
# df.Price = df.Price.apply(lambda s : float(s.replace('₹','').replace(',',''))
df.Price = df.Price.str.replace('₹','').str.replace(',','').astype(float)

print(df.Rating.dtype)
print(df.Price.dtype)
df.head()

float64
float64

,Product_name,Price,Rating,No_of_RnR,Features,PageNo
0,"vivo T5x 5G (Cyber Green, 128 GB)",22999.0,4.4,"5,888 Ratings & 390 Reviews","[6 GB RAM | 128 GB ROM, 17.17 cm (6.76 inch) D...",1
1,"IQOO Z11x 5G (Prismatic Green, 128 GB)",21745.0,4.4,430 Ratings & 38 Reviews,"[6 GB RAM | 128 GB ROM, 17.02 cm (6.7 inch) Di...",1
2,"POCO M8 Charger in the Box (Frost Silver, 256 GB)",21499.0,4.4,"1,106 Ratings & 105 Reviews","[8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,...",1
3,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,20999.0,4.4,"1,17,291 Ratings & 6,844 Reviews","[8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,...",1
4,"vivo X200T (Stellar Black, 256 GB)",59999.0,4.6,"2,173 Ratings & 376 Reviews","[12 GB RAM | 256 GB ROM, 16.94 cm (6.67 inch) ...",1

In [86]:
# Creating a regex pattern
# r'' means raw string
# ([\d,\s]+) means:
# \d  -> any digit (0-9)
# ,   -> comma
# \s  -> whitespace (space)
# +   -> one or more characters
# So this part captures:
# "3,346 "
# Ratings -> match the word "Ratings"
# Entire pattern:
# Find numbers before the word "Ratings"
text = '3,346 Ratings & 223 Reviews'
rating_regex = re.compile(r'([\d,\s]+)Ratings')
ratings = rating_regex.findall(text)
int(ratings[0].strip().replace(',',''))

3346

In [87]:
# creating functions to get number of ratings and number of reviews
def get_ratings(text):
    if text is np.nan:
        return 0
    else:
        rating_regex = re.compile(r'([\d,\s]+)Ratings')
        ratings = rating_regex.findall(text)
        ratings = int(ratings[0].strip().replace(',',''))
        return ratings
    
def get_reviews(text):
    if text is np.nan:
        return 0
    else:
        review_regex = re.compile(r'([\d,\s]+)Reviews')
        reviews = review_regex.findall(text)
        reviews = int(reviews[0].strip().replace(',',''))
        return reviews
    
print(get_ratings('3,346 Ratings & 223 Reviews'))
print(get_reviews('3,346 Ratings & 223 Reviews'))

3346
223

In [88]:
# Creating columns No_of_ratings and No_of_reviews
df['No_of_ratings'] = df.No_of_RnR.apply(get_ratings)
df['No_of_reviews'] = df.No_of_RnR.apply(get_reviews)
df.drop('No_of_RnR', axis = 1, inplace = True)
df.head(10)

,Product_name,Price,Rating,Features,PageNo,No_of_ratings,No_of_reviews
0,"vivo T5x 5G (Cyber Green, 128 GB)",22999.0,4.4,"[6 GB RAM | 128 GB ROM, 17.17 cm (6.76 inch) D...",1,5888,390
1,"IQOO Z11x 5G (Prismatic Green, 128 GB)",21745.0,4.4,"[6 GB RAM | 128 GB ROM, 17.02 cm (6.7 inch) Di...",1,430,38
2,"POCO M8 Charger in the Box (Frost Silver, 256 GB)",21499.0,4.4,"[8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,...",1,1106,105
3,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,20999.0,4.4,"[8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,...",1,117291,6844
4,"vivo X200T (Stellar Black, 256 GB)",59999.0,4.6,"[12 GB RAM | 256 GB ROM, 16.94 cm (6.67 inch) ...",1,2173,376
5,"MOTOROLA Edge 60 Fusion 5G (PANTONE Amazonite,...",20999.0,4.4,"[8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,...",1,117291,6844
6,"MOTOROLA Edge 60 Fusion 5G (PANTONE Zephyr, 12...",20999.0,4.4,"[8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,...",1,117291,6844
7,"realme P4x 5G (Matte Silver, 256 GB)",20999.0,4.3,"[8 GB RAM | 256 GB ROM, 17.07 cm (6.72 inch) F...",1,4649,347
8,"Ai+ NovaFlip 5G (Glacier White, 256 GB)",39999.0,4.2,"[8 GB RAM | 256 GB ROM, 17.53 cm (6.9 inch) Fu...",1,6,1
9,"Samsung Galaxy S25 FE 5G (Navy, 256 GB)",50999.0,4.6,"[8 GB RAM | 256 GB ROM, 17.02 cm (6.7 inch) Fu...",1,621,61

In [89]:
# Creating a regex to extract brand
brand_regex = re.compile(r'^\w+')
brand_regex.findall('CMF by Nothing Phone 2 Pro')[0]

'CMF'

In [90]:
# creating a brand column
df['Brand'] = df.Product_name.apply(lambda s : brand_regex.findall(s)[0])
df.head(10)

,Product_name,Price,Rating,Features,PageNo,No_of_ratings,No_of_reviews,Brand
0,"vivo T5x 5G (Cyber Green, 128 GB)",22999.0,4.4,"[6 GB RAM | 128 GB ROM, 17.17 cm (6.76 inch) D...",1,5888,390,vivo
1,"IQOO Z11x 5G (Prismatic Green, 128 GB)",21745.0,4.4,"[6 GB RAM | 128 GB ROM, 17.02 cm (6.7 inch) Di...",1,430,38,IQOO
2,"POCO M8 Charger in the Box (Frost Silver, 256 GB)",21499.0,4.4,"[8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,...",1,1106,105,POCO
3,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,20999.0,4.4,"[8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,...",1,117291,6844,MOTOROLA
4,"vivo X200T (Stellar Black, 256 GB)",59999.0,4.6,"[12 GB RAM | 256 GB ROM, 16.94 cm (6.67 inch) ...",1,2173,376,vivo
5,"MOTOROLA Edge 60 Fusion 5G (PANTONE Amazonite,...",20999.0,4.4,"[8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,...",1,117291,6844,MOTOROLA
6,"MOTOROLA Edge 60 Fusion 5G (PANTONE Zephyr, 12...",20999.0,4.4,"[8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,...",1,117291,6844,MOTOROLA
7,"realme P4x 5G (Matte Silver, 256 GB)",20999.0,4.3,"[8 GB RAM | 256 GB ROM, 17.07 cm (6.72 inch) F...",1,4649,347,realme
8,"Ai+ NovaFlip 5G (Glacier White, 256 GB)",39999.0,4.2,"[8 GB RAM | 256 GB ROM, 17.53 cm (6.9 inch) Fu...",1,6,1,Ai
9,"Samsung Galaxy S25 FE 5G (Navy, 256 GB)",50999.0,4.6,"[8 GB RAM | 256 GB ROM, 17.02 cm (6.7 inch) Fu...",1,621,61,Samsung

In [91]:
# Converting features list to string  (to work with regular expressions)
df.Features = df.Features.apply(lambda x : ','.join(x))
df.head(10)

,Product_name,Price,Rating,Features,PageNo,No_of_ratings,No_of_reviews,Brand
0,"vivo T5x 5G (Cyber Green, 128 GB)",22999.0,4.4,"6 GB RAM | 128 GB ROM,17.17 cm (6.76 inch) Dis...",1,5888,390,vivo
1,"IQOO Z11x 5G (Prismatic Green, 128 GB)",21745.0,4.4,"6 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Disp...",1,430,38,IQOO
2,"POCO M8 Charger in the Box (Frost Silver, 256 GB)",21499.0,4.4,"8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,1...",1,1106,105,POCO
3,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,20999.0,4.4,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1...",1,117291,6844,MOTOROLA
4,"vivo X200T (Stellar Black, 256 GB)",59999.0,4.6,"12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Fu...",1,2173,376,vivo
5,"MOTOROLA Edge 60 Fusion 5G (PANTONE Amazonite,...",20999.0,4.4,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1...",1,117291,6844,MOTOROLA
6,"MOTOROLA Edge 60 Fusion 5G (PANTONE Zephyr, 12...",20999.0,4.4,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1...",1,117291,6844,MOTOROLA
7,"realme P4x 5G (Matte Silver, 256 GB)",20999.0,4.3,"8 GB RAM | 256 GB ROM,17.07 cm (6.72 inch) Ful...",1,4649,347,realme
8,"Ai+ NovaFlip 5G (Glacier White, 256 GB)",39999.0,4.2,"8 GB RAM | 256 GB ROM,17.53 cm (6.9 inch) Full...",1,6,1,Ai
9,"Samsung Galaxy S25 FE 5G (Navy, 256 GB)",50999.0,4.6,"8 GB RAM | 256 GB ROM,17.02 cm (6.7 inch) Full...",1,621,61,Samsung

In [92]:
text = df.Features[0]
processor_regex = re.compile(r'([A-Za-z0-9\s]+)Processor')
processor_regex.findall(text)[0].strip()

'Turbo'

In [93]:
def get_processor(text):
    processor_regex = re.compile(r'([A-Za-z0-9\s]+)Processor')
    processor = processor_regex.findall(text)
    if len(processor) == 0:
        return np.nan
    else:
        return processor[0].strip()
    
get_processor(text)

'Turbo'

In [94]:
# Creating a Processor column
df['Processor'] = df.Features.apply(get_processor)
df.head(5)

,Product_name,Price,Rating,Features,PageNo,No_of_ratings,No_of_reviews,Brand,Processor
0,"vivo T5x 5G (Cyber Green, 128 GB)",22999.0,4.4,"6 GB RAM | 128 GB ROM,17.17 cm (6.76 inch) Dis...",1,5888,390,vivo,Turbo
1,"IQOO Z11x 5G (Prismatic Green, 128 GB)",21745.0,4.4,"6 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Disp...",1,430,38,IQOO,NaN
2,"POCO M8 Charger in the Box (Frost Silver, 256 GB)",21499.0,4.4,"8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,1...",1,1106,105,POCO,NaN
3,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,20999.0,4.4,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1...",1,117291,6844,MOTOROLA,Dimensity 7400
4,"vivo X200T (Stellar Black, 256 GB)",59999.0,4.6,"12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Fu...",1,2173,376,vivo,

In [95]:
# Creating a regular expression to extract RAM
text = df.Features[0]
RAM_regex = re.compile(r'([A-Za-z0-9\s]+)RAM')
RAM_regex.findall(text)[0].strip()

'6 GB'

In [96]:
def get_ram(text):
    regex = re.compile(r'([A-Za-z0-9\s]+)RAM')
    result = regex.findall(text)
    if len(result) == 0:
        return np.nan
    else:
        return result[0].strip()
    
get_ram(text)

'6 GB'

In [97]:
df['RAM'] = df.Features.apply(get_ram)
df.head(5)

,Product_name,Price,Rating,Features,PageNo,No_of_ratings,No_of_reviews,Brand,Processor,RAM
0,"vivo T5x 5G (Cyber Green, 128 GB)",22999.0,4.4,"6 GB RAM | 128 GB ROM,17.17 cm (6.76 inch) Dis...",1,5888,390,vivo,Turbo,6 GB
1,"IQOO Z11x 5G (Prismatic Green, 128 GB)",21745.0,4.4,"6 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Disp...",1,430,38,IQOO,NaN,6 GB
2,"POCO M8 Charger in the Box (Frost Silver, 256 GB)",21499.0,4.4,"8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,1...",1,1106,105,POCO,NaN,8 GB
3,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,20999.0,4.4,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1...",1,117291,6844,MOTOROLA,Dimensity 7400,8 GB
4,"vivo X200T (Stellar Black, 256 GB)",59999.0,4.6,"12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Fu...",1,2173,376,vivo,,12 GB

In [98]:
# Creating a regular expression to extract ROM
text = df.Features[0]
ROM_regex = re.compile(r'([A-Za-z0-9\s]+)ROM')
ROM_regex.findall(text)[0].strip()

'128 GB'

In [99]:
def get_rom(text):
    regex = re.compile(r'([A-Za-z0-9\s]+)ROM')
    result = regex.findall(text)
    if len(result) == 0:
        return np.nan
    else:
        return result[0].strip()
    
get_rom(text)

'128 GB'

In [100]:
df['ROM'] = df.Features.apply(get_rom)
df.head(5)

,Product_name,Price,Rating,Features,PageNo,No_of_ratings,No_of_reviews,Brand,Processor,RAM,ROM
0,"vivo T5x 5G (Cyber Green, 128 GB)",22999.0,4.4,"6 GB RAM | 128 GB ROM,17.17 cm (6.76 inch) Dis...",1,5888,390,vivo,Turbo,6 GB,128 GB
1,"IQOO Z11x 5G (Prismatic Green, 128 GB)",21745.0,4.4,"6 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Disp...",1,430,38,IQOO,NaN,6 GB,128 GB
2,"POCO M8 Charger in the Box (Frost Silver, 256 GB)",21499.0,4.4,"8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,1...",1,1106,105,POCO,NaN,8 GB,256 GB
3,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,20999.0,4.4,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1...",1,117291,6844,MOTOROLA,Dimensity 7400,8 GB,128 GB
4,"vivo X200T (Stellar Black, 256 GB)",59999.0,4.6,"12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Fu...",1,2173,376,vivo,,12 GB,256 GB

In [101]:
df.Features[0]

'6 GB RAM | 128 GB ROM,17.17 cm (6.76 inch) Display,50MP + 2MP | 32MP Front Camera,7200 mAh Li-ion Battery,Dimensity 7400-Turbo Processor,1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories'

In [102]:
# Creating a regular expression to extract Battery
text = df.Features[0]
battery_regex = re.compile(r'[A-Za-z0-9\s]+mAh')
battery_regex.findall(text)[0].strip()

'7200 mAh'

In [103]:
def get_battery(text):
    regex = re.compile(r'[A-Za-z0-9\s]+mAh')
    result = regex.findall(text)
    if len(result) == 0:
        return np.nan
    else:
        return result[0].strip()
    
get_battery(text)

'7200 mAh'

In [104]:
df['Battery'] = df.Features.apply(get_battery)
df.head(5)

,Product_name,Price,Rating,Features,PageNo,No_of_ratings,No_of_reviews,Brand,Processor,RAM,ROM,Battery
0,"vivo T5x 5G (Cyber Green, 128 GB)",22999.0,4.4,"6 GB RAM | 128 GB ROM,17.17 cm (6.76 inch) Dis...",1,5888,390,vivo,Turbo,6 GB,128 GB,7200 mAh
1,"IQOO Z11x 5G (Prismatic Green, 128 GB)",21745.0,4.4,"6 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Disp...",1,430,38,IQOO,NaN,6 GB,128 GB,7200 mAh
2,"POCO M8 Charger in the Box (Frost Silver, 256 GB)",21499.0,4.4,"8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,1...",1,1106,105,POCO,NaN,8 GB,256 GB,5520 mAh
3,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,20999.0,4.4,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1...",1,117291,6844,MOTOROLA,Dimensity 7400,8 GB,128 GB,5500 mAh
4,"vivo X200T (Stellar Black, 256 GB)",59999.0,4.6,"12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Fu...",1,2173,376,vivo,,12 GB,256 GB,6200 mAh

In [105]:
text = df.Features[0]
display_regex = re.compile(r'[0-9\s.]+inch')
display_regex.findall(text)[0].strip()

'6.76 inch'

In [106]:
def get_display(text):
    regex = re.compile(r'[0-9\s.]+inch')
    result = regex.findall(text)
    if len(result) == 0:
        return np.nan
    else:
        return result[0].strip()
    
get_display(text)

'6.76 inch'

In [107]:
df['Display_Size'] = df.Features.apply(get_display)
df.head()

,Product_name,Price,Rating,Features,PageNo,No_of_ratings,No_of_reviews,Brand,Processor,RAM,ROM,Battery,Display_Size
0,"vivo T5x 5G (Cyber Green, 128 GB)",22999.0,4.4,"6 GB RAM | 128 GB ROM,17.17 cm (6.76 inch) Dis...",1,5888,390,vivo,Turbo,6 GB,128 GB,7200 mAh,6.76 inch
1,"IQOO Z11x 5G (Prismatic Green, 128 GB)",21745.0,4.4,"6 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Disp...",1,430,38,IQOO,NaN,6 GB,128 GB,7200 mAh,6.7 inch
2,"POCO M8 Charger in the Box (Frost Silver, 256 GB)",21499.0,4.4,"8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,1...",1,1106,105,POCO,NaN,8 GB,256 GB,5520 mAh,6.77 inch
3,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,20999.0,4.4,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1...",1,117291,6844,MOTOROLA,Dimensity 7400,8 GB,128 GB,5500 mAh,6.67 inch
4,"vivo X200T (Stellar Black, 256 GB)",59999.0,4.6,"12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Fu...",1,2173,376,vivo,,12 GB,256 GB,6200 mAh,6.67 inch

In [108]:
# Creating a regular expression to extract Camera info
text = df.Features[0]
camera_regex = re.compile(r'[A-Za-z0-9\s\(\)\+\|]+Camera')
camera_regex.findall(text)[0].strip()

'50MP + 2MP | 32MP Front Camera'

In [109]:
def get_camera(text):
    regex = re.compile(r'[A-Za-z0-9\s\(\)\+\|]+Camera')
    result = regex.findall(text)
    if len(result) == 0:
        return np.nan
    else:
        return result[0].strip()
    
get_camera(text)

'50MP + 2MP | 32MP Front Camera'

In [110]:
df['Camera'] = df.Features.apply(get_camera)
df.head()

,Product_name,Price,Rating,Features,PageNo,No_of_ratings,No_of_reviews,Brand,Processor,RAM,ROM,Battery,Display_Size,Camera
0,"vivo T5x 5G (Cyber Green, 128 GB)",22999.0,4.4,"6 GB RAM | 128 GB ROM,17.17 cm (6.76 inch) Dis...",1,5888,390,vivo,Turbo,6 GB,128 GB,7200 mAh,6.76 inch,50MP + 2MP | 32MP Front Camera
1,"IQOO Z11x 5G (Prismatic Green, 128 GB)",21745.0,4.4,"6 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Disp...",1,430,38,IQOO,NaN,6 GB,128 GB,7200 mAh,6.7 inch,50MP Rear Camera
2,"POCO M8 Charger in the Box (Frost Silver, 256 GB)",21499.0,4.4,"8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,1...",1,1106,105,POCO,NaN,8 GB,256 GB,5520 mAh,6.77 inch,50MP Rear Camera | 20MP Front Camera
3,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,20999.0,4.4,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1...",1,117291,6844,MOTOROLA,Dimensity 7400,8 GB,128 GB,5500 mAh,6.67 inch,50MP + 13MP | 32MP Front Camera
4,"vivo X200T (Stellar Black, 256 GB)",59999.0,4.6,"12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Fu...",1,2173,376,vivo,,12 GB,256 GB,6200 mAh,6.67 inch,50MP + 50MP + 50MP | 32MP Front Camera

In [111]:
# Removing Features Column
df.drop(['Features', 'PageNo'], axis = 1, inplace = True)
df.head()

,Product_name,Price,Rating,No_of_ratings,No_of_reviews,Brand,Processor,RAM,ROM,Battery,Display_Size,Camera
0,"vivo T5x 5G (Cyber Green, 128 GB)",22999.0,4.4,5888,390,vivo,Turbo,6 GB,128 GB,7200 mAh,6.76 inch,50MP + 2MP | 32MP Front Camera
1,"IQOO Z11x 5G (Prismatic Green, 128 GB)",21745.0,4.4,430,38,IQOO,NaN,6 GB,128 GB,7200 mAh,6.7 inch,50MP Rear Camera
2,"POCO M8 Charger in the Box (Frost Silver, 256 GB)",21499.0,4.4,1106,105,POCO,NaN,8 GB,256 GB,5520 mAh,6.77 inch,50MP Rear Camera | 20MP Front Camera
3,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,20999.0,4.4,117291,6844,MOTOROLA,Dimensity 7400,8 GB,128 GB,5500 mAh,6.67 inch,50MP + 13MP | 32MP Front Camera
4,"vivo X200T (Stellar Black, 256 GB)",59999.0,4.6,2173,376,vivo,,12 GB,256 GB,6200 mAh,6.67 inch,50MP + 50MP + 50MP | 32MP Front Camera

In [112]:
# rearranging the columns
columns = ['Brand', 'Product_name','Processor', 'RAM', 'ROM', 'Battery', 'Display_Size', 'Camera', 'No_of_ratings', 'No_of_reviews', 'Rating', 'Price']
df = df[columns]
df.head(10)

,Brand,Product_name,Processor,RAM,ROM,Battery,Display_Size,Camera,No_of_ratings,No_of_reviews,Rating,Price
0,vivo,"vivo T5x 5G (Cyber Green, 128 GB)",Turbo,6 GB,128 GB,7200 mAh,6.76 inch,50MP + 2MP | 32MP Front Camera,5888,390,4.4,22999.0
1,IQOO,"IQOO Z11x 5G (Prismatic Green, 128 GB)",NaN,6 GB,128 GB,7200 mAh,6.7 inch,50MP Rear Camera,430,38,4.4,21745.0
2,POCO,"POCO M8 Charger in the Box (Frost Silver, 256 GB)",NaN,8 GB,256 GB,5520 mAh,6.77 inch,50MP Rear Camera | 20MP Front Camera,1106,105,4.4,21499.0
3,MOTOROLA,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,Dimensity 7400,8 GB,128 GB,5500 mAh,6.67 inch,50MP + 13MP | 32MP Front Camera,117291,6844,4.4,20999.0
4,vivo,"vivo X200T (Stellar Black, 256 GB)",,12 GB,256 GB,6200 mAh,6.67 inch,50MP + 50MP + 50MP | 32MP Front Camera,2173,376,4.6,59999.0
5,MOTOROLA,"MOTOROLA Edge 60 Fusion 5G (PANTONE Amazonite,...",Dimensity 7400,8 GB,128 GB,5500 mAh,6.67 inch,50MP + 13MP | 32MP Front Camera,117291,6844,4.4,20999.0
6,MOTOROLA,"MOTOROLA Edge 60 Fusion 5G (PANTONE Zephyr, 12...",Dimensity 7400,8 GB,128 GB,5500 mAh,6.67 inch,50MP + 13MP | 32MP Front Camera,117291,6844,4.4,20999.0
7,realme,"realme P4x 5G (Matte Silver, 256 GB)",Dimensity 7400 Ultra,8 GB,256 GB,7000 mAh,6.72 inch,50MP + 2MP | 8MP Front Camera,4649,347,4.3,20999.0
8,Ai,"Ai+ NovaFlip 5G (Glacier White, 256 GB)",NaN,8 GB,256 GB,4325 mAh,6.9 inch,50MP + 2MP | 32MP Front Camera,6,1,4.2,39999.0
9,Samsung,"Samsung Galaxy S25 FE 5G (Navy, 256 GB)",Exynos 2400,8 GB,256 GB,4900 mAh,6.7 inch,50MP + 12MP + 8MP | 12MP Front Camera,621,61,4.6,50999.0

In [113]:
df.to_csv('Flipkart Phones.csv', index = False)